import {
  Component,
  useCallback,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import { useTranslation } from 'react-i18next';
import { useQuery } from '@tanstack/react-query';
import type { ClusterMetricsSnapshot, MetricsNode } from 'shared/types';

import { useJsonPatchWsStream } from '@/shared/hooks/useJsonPatchWsStream';
import { clusterMetricsApi } from '@/shared/lib/api';
import { clusterMetricsKeys } from '@/shared/lib/clusterMetricsKeys';
import { useHostId } from '@/shared/providers/HostIdProvider';
import {
  CPU_PANEL_ID,
  CpuPanel,
} from '@/shared/components/ui-new/views/metrics/CpuPanel';
import {
  DISKS_PANEL_ID,
  DisksPanel,
} from '@/shared/components/ui-new/views/metrics/DisksPanel';
import {
  MEMORY_PANEL_ID,
  MemoryPanel,
} from '@/shared/components/ui-new/views/metrics/MemoryPanel';
import {
  NETWORK_PANEL_ID,
  NetworkPanel,
} from '@/shared/components/ui-new/views/metrics/NetworkPanel';
import {
  PROCESSES_PANEL_ID,
  ProcessesPanel,
} from '@/shared/components/ui-new/views/metrics/ProcessesPanel';
import {
  NodeStrip,
  hasNoCurrentReadings,
  isStale,
} from '@/shared/components/ui-new/views/metrics/NodeStrip';
import { ratioPercent } from '@/shared/components/ui-new/views/metrics/format';
import {
  classifyNode,
  DEFAULT_DISK_ALERT_THRESHOLDS,
} from '@/shared/components/ui-new/views/metrics/diskAlerts';
import { useAppNavigation } from '@/shared/hooks/useAppNavigation';
import { createShapeCollection } from '@/shared/lib/electric/collections';
import { PROJECT_ISSUES_SHAPE } from 'shared/remote-types';

/** The live stream, host-scoped by the transport when a host id is present. */
const METRICS_WS_PATH = '/cluster/metrics/ws';

/**
 * Cadence of the REST fallback poll. Only runs while the socket has not
 * delivered its `Ready`, so a healthy stream costs nothing.
 */
const FALLBACK_POLL_MS = 5000;

/**
 * Seed cadence, replaced by the server's own `sample_interval_ms` as soon as
 * a snapshot lands.
 */
export const DEFAULT_SAMPLE_INTERVAL_MS = 2000;

/**
 * The snapshot *as the client holds it*.
 *
 * Two deliberate widenings over the generated `ClusterMetricsSnapshot`:
 *
 * - `generated_at` is nullable, because the seed the stream starts from has
 *   not been generated by anything yet. The path must nevertheless **exist**:
 *   the server's resnapshot emits `replace /generated_at` and `replace /nodes`
 *   (never the document root), and `applyUpsertPatch` can only rewrite a
 *   failed `replace` into an `add` when the parent object is there.
 * - `sample_interval_ms` is `bigint | number`, because `ts-rs` maps Rust's
 *   `u64` to `bigint` while `JSON.parse` hands us a `number` for the same
 *   wire value.
 */
export type MetricsStreamSnapshot = Omit<
  ClusterMetricsSnapshot,
  'generated_at' | 'sample_interval_ms'
> & {
  generated_at: string | null;
  sample_interval_ms: bigint | number;
};

/** Which detail panels start open when a node is first expanded. */
const DEFAULT_PANEL_EXPANDED: Record<string, boolean> = {
  [CPU_PANEL_ID]: true,
  [MEMORY_PANEL_ID]: true,
  [DISKS_PANEL_ID]: false,
  [NETWORK_PANEL_ID]: false,
  [PROCESSES_PANEL_ID]: false,
};

/**
 * Thrown to discard a snapshot that resolved *after* the host scope moved.
 *
 * `/api/cluster/metrics` describes whichever host routed the request, so a
 * late response from host A filed against host B would render one machine's
 * readings under another's hostname.
 */
class StaleHostSnapshotError extends Error {
  constructor() {
    super('cluster metrics snapshot resolved after a host switch');
    this.name = 'StaleHostSnapshotError';
  }
}

/**
 * One node's readings must not be able to blank the sidebar.
 *
 * A malformed node — a missing `availability`, a sample shaped differently by
 * an older worker — throws inside that node's subtree only, and every other
 * node keeps rendering.
 */
class NodeErrorBoundary extends Component<
  { fallback: ReactNode; children: ReactNode },
  { hasError: boolean }
> {
  state = { hasError: false };

  static getDerivedStateFromError() {
    return { hasError: true };
  }

  componentDidCatch(error: unknown) {
    console.error('Server metrics node crashed:', error);
  }

  render() {
    return this.state.hasError ? this.props.fallback : this.props.children;
  }
}

/** Coordinator first, then workers by hostname. Never throws on bad data. */
function compareNodes(a: MetricsNode, b: MetricsNode): number {
  const rank = (node: MetricsNode) => (node?.role === 'coordinator' ? 0 : 1);
  const byRank = rank(a) - rank(b);
  if (byRank !== 0) return byRank;
  return String(a?.hostname ?? '').localeCompare(String(b?.hostname ?? ''));
}

/** Total-busy percentage per retained sample, oldest first. */
function cpuHistory(node: MetricsNode): (number | null)[] {
  return (node.history ?? []).map(
    (sample) => sample?.cpu?.total_busy_percent ?? null
  );
}

/** Used-memory percentage per retained sample, oldest first. */
function memoryHistory(node: MetricsNode): (number | null)[] {
  return (node.history ?? []).map((sample) =>
    ratioPercent(sample?.memory?.used_bytes, sample?.memory?.total_bytes)
  );
}

export interface ServerMetricsSectionContainerProps {
  projectId?: string | null;
  /**
   * Whether the sidebar section showing this container is open.
   *
   * `CollapsibleSectionHeader` unmounts its children while collapsed, so the
   * default is `true` and the structural guarantee already holds; the prop
   * exists so a caller that keeps the container mounted — and the tests — can
   * assert the socket stays shut.
   */
  expanded?: boolean;
}

/**
 * The "Server metrics" section of the workspace right sidebar.
 *
 * Live over `/api/cluster/metrics/ws`, with `/api/cluster/metrics` as the
 * fallback. The fallback is what makes an unhappy socket survivable: a
 * `WebSocket` constructor resolves before the HTTP upgrade has been accepted,
 * so a rejected upgrade surfaces as an `error` and a `close` on an object that
 * already looked fine. `useJsonPatchWsStream` retries those with backoff, and
 * until it reports `Ready` this container keeps polling REST and says so — the
 * section never sits in "connecting" with nothing in it.
 */
export function ServerMetricsSectionContainer({
  expanded = true,
  projectId = null,
}: ServerMetricsSectionContainerProps) {
  const { t } = useTranslation('common');
  const hostId = useHostId();
  const appNavigation = useAppNavigation();
  const [resolvingNodeId, setResolvingNodeId] = useState<string | null>(null);
  const [diskActionError, setDiskActionError] = useState<string | null>(null);

  const [selectedNodeId, setSelectedNodeId] = useState<string | null>(null);
  const [panelOverrides, setPanelOverrides] = useState<Record<string, boolean>>(
    {}
  );

  const endpoint = useMemo(
    () =>
      hostId
        ? `/api/host/${hostId}${METRICS_WS_PATH}`
        : `/api${METRICS_WS_PATH}`,
    [hostId]
  );

  const initialData = useCallback(
    (): MetricsStreamSnapshot => ({
      // Both patched paths must exist before the first resnapshot lands.
      nodes: {},
      generated_at: null,
      sample_interval_ms: DEFAULT_SAMPLE_INTERVAL_MS,
      disk_alert_thresholds: DEFAULT_DISK_ALERT_THRESHOLDS,
    }),
    []
  );

  const {
    data: streamData,
    isInitialized,
    isConnected,
    error: streamError,
  } = useJsonPatchWsStream<MetricsStreamSnapshot>(
    endpoint,
    expanded,
    initialData
  );

  // Bumped by every fetch, so only the newest one is allowed to resolve into
  // the cache. React Query already partitions by key; this guards the window
  // in which a request issued for the previous host is still in flight.
  const generationRef = useRef(0);

  const fallbackQuery = useQuery({
    queryKey: clusterMetricsKeys.snapshot(hostId),
    queryFn: async ({ signal }) => {
      const generation = (generationRef.current += 1);
      const snapshot = await clusterMetricsApi.snapshot(hostId, { signal });
      if (generation !== generationRef.current) {
        throw new StaleHostSnapshotError();
      }
      return snapshot;
    },
    enabled: expanded && !isInitialized,
    refetchInterval: FALLBACK_POLL_MS,
    retry: false,
  });

  const snapshot: MetricsStreamSnapshot | undefined =
    isInitialized && streamData ? streamData : fallbackQuery.data;

  const nodes = useMemo(() => {
    const entries = Object.values(snapshot?.nodes ?? {}).filter(
      (node): node is MetricsNode => !!node
    );
    return entries.sort(compareNodes);
  }, [snapshot]);

  const resolveDiskAlert = useCallback(
    async (nodeId: string) => {
      if (!projectId || resolvingNodeId) return;
      setResolvingNodeId(nodeId);
      setDiskActionError(null);
      try {
        const node = nodes.find((candidate) => candidate.node_id === nodeId);
        if (!node?.latest)
          throw new Error('The disk reading is no longer available.');
        const response = await clusterMetricsApi.resolveLowDiskIssue(
          {
            project_id: projectId,
            node_id: nodeId,
            hostname: node.hostname,
            observed_at: node.latest.captured_at,
            filesystems: [],
          },
          hostId
        );
        const issues = createShapeCollection(PROJECT_ISSUES_SHAPE, {
          project_id: projectId,
        });
        await issues.utils.awaitTxId(Number(response.txid), 10_000);
        appNavigation.goToProjectIssue(projectId, response.issue.id);
      } catch (error) {
        setDiskActionError(
          error instanceof Error ? error.message : String(error)
        );
      } finally {
        setResolvingNodeId(null);
      }
    },
    [appNavigation, hostId, nodes, projectId, resolvingNodeId]
  );

  const togglePanel = useCallback((panelId: string) => {
    setPanelOverrides((current) => ({
      ...current,
      [panelId]: !(
        current[panelId] ??
        DEFAULT_PANEL_EXPANDED[panelId] ??
        false
      ),
    }));
  }, []);

  const selectNode = useCallback((nodeId: string) => {
    setSelectedNodeId((current) => (current === nodeId ? null : nodeId));
  }, []);

  const panelExpanded = useCallback(
    (panelId: string) =>
      panelOverrides[panelId] ?? DEFAULT_PANEL_EXPANDED[panelId] ?? false,
    [panelOverrides]
  );

  const streamStatus = (() => {
    if (isInitialized && isConnected) return null;
    if (streamError) {
      return t('metrics.stream.error', {
        defaultValue: 'Live updates unavailable ({{error}}) — polling instead.',
        error: streamError,
      });
    }
    return t('metrics.stream.connecting', {
      defaultValue: 'Connecting to live updates — polling instead.',
    });
  })();

  return (
    <div
      data-testid="server-metrics-section"
      // Both axes are pinned: a `visible` axis next to a scrolling one
      // computes to `auto`, which would silently add a horizontal scroller.
      className="flex flex-col flex-1 min-h-0 w-full gap-half p-base overflow-y-auto overflow-x-hidden"
    >
      {streamStatus && (
        <p data-testid="metrics-stream-status" className="text-sm text-low">
          {streamStatus}
        </p>
      )}
      {diskActionError && (
        <p role="alert" className="text-sm text-error">
          Failed to resolve low-disk issue: {diskActionError}
        </p>
      )}

      {nodes.length === 0 ? (
        <p data-testid="metrics-empty" className="text-sm text-low">
          {fallbackQuery.isPending && !isInitialized
            ? t('metrics.loading', { defaultValue: 'Reading nodes…' })
            : t('metrics.noNodes', { defaultValue: 'No nodes reporting' })}
        </p>
      ) : (
        nodes.map((node) => (
          <NodeErrorBoundary
            key={node.node_id}
            fallback={
              <p
                data-testid="metrics-node-error"
                className="text-sm text-error p-half"
              >
                {t('metrics.nodeError', {
                  defaultValue: 'This node reported readings we cannot show.',
                })}
              </p>
            }
          >
            <div data-testid="metrics-node" className="flex flex-col">
              <NodeStrip
                node={node}
                selected={selectedNodeId === node.node_id}
                onSelect={selectNode}
                diskAlert={
                  snapshot
                    ? classifyNode(node, snapshot.disk_alert_thresholds)
                    : null
                }
                onResolveDiskAlert={projectId ? resolveDiskAlert : undefined}
                resolvingDiskAlert={resolvingNodeId === node.node_id}
                diskAlertActionDisabledReason={
                  projectId
                    ? null
                    : 'Link this workspace to a project to create an issue.'
                }
              />
              {selectedNodeId === node.node_id && (
                <NodeDetail
                  node={node}
                  panelExpanded={panelExpanded}
                  onTogglePanel={togglePanel}
                />
              )}
            </div>
          </NodeErrorBoundary>
        ))
      )}
    </div>
  );
}

/**
 * The expanded node's panels.
 *
 * A node with no *current* readings and nothing retained renders its
 * availability reason instead of a wall of panels — never a wall of zeros. A
 * `stale` node is the exception: its retained readings are shown, dimmed, and
 * labelled with when they were captured.
 */
function NodeDetail({
  node,
  panelExpanded,
  onTogglePanel,
}: {
  node: MetricsNode;
  panelExpanded: (panelId: string) => boolean;
  onTogglePanel: (panelId: string) => void;
}) {
  const { t } = useTranslation('common');
  const stale = isStale(node.availability);
  const latest = node.latest;

  if (!latest && hasNoCurrentReadings(node.availability)) {
    return (
      <p
        data-testid="metrics-node-no-readings"
        className="text-sm text-low p-half"
      >
        {t('metrics.noReadings', {
          defaultValue: 'No readings for this node',
        })}
      </p>
    );
  }

  return (
    <div data-testid="metrics-node-detail" className="flex flex-col px-half">
      <CpuPanel
        cpu={latest?.cpu ?? null}
        history={cpuHistory(node)}
        expanded={panelExpanded(CPU_PANEL_ID)}
        onToggle={onTogglePanel}
        stale={stale}
      />
      <MemoryPanel
        memory={latest?.memory ?? null}
        history={memoryHistory(node)}
        expanded={panelExpanded(MEMORY_PANEL_ID)}
        onToggle={onTogglePanel}
        stale={stale}
      />
      <DisksPanel
        filesystems={latest?.filesystems ?? null}
        expanded={panelExpanded(DISKS_PANEL_ID)}
        onToggle={onTogglePanel}
        stale={stale}
      />
      <NetworkPanel
        networks={latest?.networks ?? null}
        expanded={panelExpanded(NETWORK_PANEL_ID)}
        onToggle={onTogglePanel}
        stale={stale}
      />
      <ProcessesPanel
        processes={latest?.processes ?? null}
        expanded={panelExpanded(PROCESSES_PANEL_ID)}
        onToggle={onTogglePanel}
        stale={stale}
      />
    </div>
  );
}
