use std::{path::Path, sync::Arc};

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use tokio::process::Command;
use ts_rs::TS;
use workspace_utils::{command_ext::GroupSpawnNoWindowExt, shell::get_shell_command};

use crate::{
    actions::Executable,
    approvals::ExecutorApprovalService,
    env::ExecutionEnv,
    executors::{ExecutorError, SpawnedChild},
};

/// When set in the execution environment, the script's stdout/stderr are
/// appended to this file instead of piped to the server. This detaches the
/// process from the server's lifetime: it keeps logging even if the server
/// restarts, and the (new) server tails the file. Used for dev servers.
pub const RAW_LOG_PATH_ENV: &str = "VK_RAW_LOG_PATH";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, TS)]
pub enum ScriptRequestLanguage {
    Bash,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, TS)]
pub enum ScriptContext {
    SetupScript,
    CleanupScript,
    ArchiveScript,
    DevServer,
    ToolInstallScript,
    BackgroundHelper,
}

/// Smallest and largest tick interval a poller may be created with. A poller
/// ticks for the lifetime of its workspace, so the floor keeps a chatty command
/// from behaving like a busy loop and the ceiling keeps an interval from being
/// so long the poller looks hung.
pub const MIN_POLLER_INTERVAL_SECS: u32 = 5;
pub const MAX_POLLER_INTERVAL_SECS: u32 = 86_400;

/// Backstop on the generated loop so a forgotten poller cannot tick literally
/// forever. At the minimum interval this is still several days of ticks — it
/// bounds the loop, it is not the intended lifetime (archive/stop end a poller
/// long before this).
pub const MAX_POLLER_TICKS: u32 = 100_000;

/// Bytes of combined stdout/stderr kept per tick. Nothing in the persistent
/// raw-log path rotates or truncates, and a poller ticks indefinitely, so the
/// cap is what keeps one chatty command from growing the log without limit.
pub const POLLER_TICK_OUTPUT_CAP_BYTES: u32 = 65_536;

/// What an agent asked for, retained alongside the generated `script` so a
/// poller can be *described* (command, interval) without reverse-engineering a
/// shell loop out of `ScriptRequest::script`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, TS)]
pub struct PollerSpec {
    /// The command run on each tick, as supplied by the agent.
    pub command: String,
    /// Seconds between ticks. Validated to
    /// `[MIN_POLLER_INTERVAL_SECS, MAX_POLLER_INTERVAL_SECS]`; zero is rejected.
    pub interval_secs: u32,
}

/// Whether `interval_secs` is an acceptable poller interval.
///
/// Zero is rejected on its own branch rather than left to the range check, and
/// is never quietly replaced by a default: the failure mode of a defaulted
/// interval is a hot loop, so the caller has to be told it asked for something
/// impossible.
pub fn validate_interval(interval_secs: u32) -> bool {
    if interval_secs == 0 {
        return false;
    }
    (MIN_POLLER_INTERVAL_SECS..=MAX_POLLER_INTERVAL_SECS).contains(&interval_secs)
}

/// Build the shell loop that runs a poller's command on its interval.
///
/// Properties the generated script is required to have:
/// - the loop is bounded (`MAX_POLLER_TICKS`);
/// - every tick is preceded by a timestamped delimiter, so ticks are
///   attributable in the raw log;
/// - a non-zero tick exit is reported and the loop continues — a poller that
///   died the first time its command failed would be useless;
/// - signals are *not* trapped, so `kill_process_group` still terminates it;
/// - per-tick output is capped, with an explicit marker when it was cut.
///
/// The command is interpolated as the body of a shell function rather than
/// `eval`'d out of a Rust-quoted string: there is no quoting layer to get
/// wrong, and the function is invoked on the left of a pipeline (a subshell),
/// so a `cd`, an `exit` or a stray assignment in the agent's command cannot
/// leak into the loop that drives it.
pub fn compile_poller_script(spec: &PollerSpec) -> String {
    let cap = POLLER_TICK_OUTPUT_CAP_BYTES;
    let interval = spec.interval_secs;
    let max_ticks = MAX_POLLER_TICKS;
    // The command may not end in a newline, and may end in a comment; start the
    // closing brace on its own line so the function always closes.
    let command = spec.command.trim_end_matches('\n');

    format!(
        r#"# Vibe Kanban poller (generated by compile_poller_script; do not hand-edit).
#
# Signals are deliberately left at their default disposition so the server's
# kill_process_group terminates this loop. Only EXIT is trapped, to clean up
# the scratch files.

__vk_interval={interval}
__vk_max_ticks={max_ticks}
__vk_cap={cap}
__vk_out=$(mktemp 2>/dev/null || echo "${{TMPDIR:-/tmp}}/vk-poller-$$.out")
__vk_rc=$(mktemp 2>/dev/null || echo "${{TMPDIR:-/tmp}}/vk-poller-$$.rc")
trap 'rm -f "$__vk_out" "$__vk_rc"' EXIT

# The agent's command, as a shell body.
__vk_poller_tick() {{
{command}
}}

__vk_tick=0
while [ "$__vk_tick" -lt "$__vk_max_ticks" ]; do
    __vk_tick=$((__vk_tick + 1))
    printf '=== vk-poller tick %s %s ===\n' \
        "$__vk_tick" "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

    # Read one byte past the cap so an over-cap tick is detectable, and keep
    # the scratch file bounded at cap+1 rather than at whatever the command
    # decided to emit.
    : > "$__vk_rc"
    {{ __vk_poller_tick; printf '%s' "$?" > "$__vk_rc"; }} 2>&1 \
        | head -c "$((__vk_cap + 1))" > "$__vk_out"

    __vk_bytes=$(wc -c < "$__vk_out")
    if [ "$((__vk_bytes))" -gt "$__vk_cap" ]; then
        head -c "$__vk_cap" "$__vk_out"
        printf '\n=== vk-poller tick %s output truncated at %s bytes ===\n' \
            "$__vk_tick" "$__vk_cap"
    else
        cat "$__vk_out"
    fi

    # A failing tick is reported, not fatal: the next tick still runs.
    __vk_status=$(cat "$__vk_rc" 2>/dev/null)
    if [ -n "$__vk_status" ] && [ "$__vk_status" != "0" ]; then
        printf '=== vk-poller tick %s exited %s (continuing) ===\n' \
            "$__vk_tick" "$__vk_status"
    fi

    sleep "$__vk_interval"
done

printf '=== vk-poller stopped: reached its %s-tick bound ===\n' "$__vk_max_ticks"
"#
    )
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, TS)]
pub struct ScriptRequest {
    pub script: String,
    pub language: ScriptRequestLanguage,
    pub context: ScriptContext,
    /// Optional relative path to execute the script in (relative to container_ref).
    /// If None, uses the container_ref directory directly.
    #[serde(default)]
    pub working_dir: Option<String>,
    /// Set when this script is a generated poller loop; `None` for every other
    /// script. Absent from rows written before pollers existed, which is why it
    /// is `#[serde(default)]` — `executor_action` is JSON in a TEXT column, so
    /// this stays migration-free.
    #[serde(default)]
    pub poller: Option<PollerSpec>,
}

#[async_trait]
impl Executable for ScriptRequest {
    async fn spawn(
        &self,
        current_dir: &Path,
        _approvals: Arc<dyn ExecutorApprovalService>,
        env: &ExecutionEnv,
    ) -> Result<SpawnedChild, ExecutorError> {
        // Use working_dir if specified, otherwise use current_dir
        let effective_dir = match &self.working_dir {
            Some(rel_path) => current_dir.join(rel_path),
            None => current_dir.to_path_buf(),
        };

        let (stdout, stderr) = match env.get(RAW_LOG_PATH_ENV) {
            Some(path) => {
                let file = std::fs::OpenOptions::new()
                    .create(true)
                    .append(true)
                    .open(path)?;
                let clone = file.try_clone()?;
                (
                    std::process::Stdio::from(clone),
                    std::process::Stdio::from(file),
                )
            }
            None => (std::process::Stdio::piped(), std::process::Stdio::piped()),
        };

        let (shell_cmd, shell_arg) = get_shell_command();
        let mut command = Command::new(shell_cmd);
        command
            .kill_on_drop(true)
            .stdin(std::process::Stdio::null())
            .stdout(stdout)
            .stderr(stderr)
            .arg(shell_arg)
            .arg(&self.script)
            .current_dir(&effective_dir);

        // Apply environment variables
        env.apply_to_command(&mut command);

        let child = command.group_spawn_no_window()?;

        Ok(child.into())
    }
}

#[cfg(test)]
mod poller_tests {
    use super::*;

    fn spec(command: &str, interval_secs: u32) -> PollerSpec {
        PollerSpec {
            command: command.to_string(),
            interval_secs,
        }
    }

    #[test]
    fn script_request_round_trips_with_and_without_a_poller() {
        for poller in [None, Some(spec("git fetch --dry-run", 60))] {
            let request = ScriptRequest {
                script: "echo hi".to_string(),
                language: ScriptRequestLanguage::Bash,
                context: ScriptContext::BackgroundHelper,
                working_dir: Some("repo".to_string()),
                poller,
            };

            let json = serde_json::to_string(&request).unwrap();
            let back: ScriptRequest = serde_json::from_str(&json).unwrap();

            assert_eq!(back, request);
        }
    }

    #[test]
    fn deserializes_rows_written_before_pollers_existed() {
        // `executor_action` is JSON in a TEXT column: rows written before this
        // field existed carry no `poller` key at all. They must still load, as
        // plain (non-poller) scripts.
        let legacy = r#"{
            "script": "npm run watch",
            "language": "Bash",
            "context": "BackgroundHelper",
            "working_dir": null
        }"#;

        let request: ScriptRequest = serde_json::from_str(legacy).unwrap();

        assert_eq!(request.poller, None);
        assert_eq!(request.script, "npm run watch");
    }

    #[test]
    fn accepts_intervals_on_both_bounds() {
        assert!(validate_interval(MIN_POLLER_INTERVAL_SECS));
        assert!(validate_interval(MAX_POLLER_INTERVAL_SECS));
        assert!(validate_interval(60));
    }

    #[test]
    fn rejects_zero_and_out_of_range_intervals() {
        // Zero is the one that matters: defaulting it would be a hot loop.
        assert!(!validate_interval(0));
        assert!(!validate_interval(MIN_POLLER_INTERVAL_SECS - 1));
        assert!(!validate_interval(MAX_POLLER_INTERVAL_SECS + 1));
    }

    #[test]
    fn generated_script_carries_the_command_interval_and_delimiter() {
        let script = compile_poller_script(&spec("git fetch --dry-run origin main", 90));

        assert!(script.contains("git fetch --dry-run origin main"));
        assert!(script.contains("__vk_interval=90"));
        assert!(script.contains("=== vk-poller tick %s %s ==="));
        // Bounded, not `while true`.
        assert!(script.contains(&format!("__vk_max_ticks={MAX_POLLER_TICKS}")));
        // The command is a shell body, never fed back through `eval`.
        assert!(!script.contains("eval"));
    }

    /// Run a generated poller until `needle` shows up in its output (or the
    /// timeout expires), then kill it and return everything it wrote.
    #[cfg(unix)]
    fn run_generated_poller_until(
        spec: &PollerSpec,
        needle: &str,
        timeout: std::time::Duration,
    ) -> String {
        let dir = std::env::temp_dir().join(format!("vk-poller-test-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        let log_path = dir.join("out.log");
        let log = std::fs::File::create(&log_path).unwrap();
        let log_err = log.try_clone().unwrap();

        let mut child = std::process::Command::new("bash")
            .arg("-c")
            .arg(compile_poller_script(spec))
            .stdin(std::process::Stdio::null())
            .stdout(log)
            .stderr(log_err)
            .current_dir(&dir)
            .spawn()
            .expect("spawn generated poller");

        let deadline = std::time::Instant::now() + timeout;
        while std::time::Instant::now() < deadline {
            if std::fs::read_to_string(&log_path)
                .unwrap_or_default()
                .contains(needle)
            {
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(100));
        }

        let _ = child.kill();
        let _ = child.wait();
        let output = std::fs::read_to_string(&log_path).unwrap_or_default();
        let _ = std::fs::remove_dir_all(&dir);
        output
    }

    #[cfg(unix)]
    #[test]
    fn an_over_cap_tick_is_truncated_with_a_marker() {
        let over_cap = POLLER_TICK_OUTPUT_CAP_BYTES + 4096;
        let command = format!("head -c {over_cap} /dev/zero | tr '\\0' 'x'");

        let output = run_generated_poller_until(
            &spec(&command, MIN_POLLER_INTERVAL_SECS),
            "output truncated",
            std::time::Duration::from_secs(20),
        );

        assert!(
            output.contains("output truncated at 65536 bytes"),
            "expected a truncation marker, got {} bytes: {:?}",
            output.len(),
            &output[..output.len().min(300)]
        );
        // The marker is not decoration: the tick's payload really was cut.
        let payload = output.matches('x').count();
        assert!(
            payload <= POLLER_TICK_OUTPUT_CAP_BYTES as usize,
            "tick emitted {payload} capped bytes, cap is {POLLER_TICK_OUTPUT_CAP_BYTES}"
        );
    }

    #[cfg(unix)]
    #[test]
    fn a_failing_tick_does_not_end_the_loop() {
        // The whole point of a poller: the thing it watches is allowed to be
        // broken. A non-zero tick must be reported and then followed by
        // another tick.
        let output = run_generated_poller_until(
            &spec("echo watching; exit 3", MIN_POLLER_INTERVAL_SECS),
            "=== vk-poller tick 2 ",
            std::time::Duration::from_secs(30),
        );

        assert!(
            output.contains("exited 3 (continuing)"),
            "expected the failing tick to be reported: {output:?}"
        );
        assert!(
            output.contains("=== vk-poller tick 2 "),
            "expected a second tick after a failing first tick: {output:?}"
        );
    }
}

#[cfg(all(test, unix))]
mod tests {
    use std::sync::Arc;

    use super::*;
    use crate::{
        approvals::NoopExecutorApprovalService,
        env::{ExecutionEnv, RepoContext},
    };

    #[tokio::test]
    async fn redirects_output_to_raw_log_file_when_env_set() {
        let dir = std::env::temp_dir().join(format!("vk-script-test-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        let log_path = dir.join("out.raw.log");

        let request = ScriptRequest {
            script: "echo hello-raw-log".to_string(),
            language: ScriptRequestLanguage::Bash,
            context: ScriptContext::DevServer,
            working_dir: None,
            poller: None,
        };
        let mut env =
            ExecutionEnv::new(RepoContext::new(dir.clone(), vec![]), false, String::new());
        env.insert(RAW_LOG_PATH_ENV, log_path.to_string_lossy().into_owned());

        let mut spawned = request
            .spawn(&dir, Arc::new(NoopExecutorApprovalService), &env)
            .await
            .unwrap();
        // With redirected stdio there are no pipes to consume
        assert!(spawned.child.inner().stdout.is_none());
        spawned.child.wait().await.unwrap();

        let content = std::fs::read_to_string(&log_path).unwrap();
        assert!(content.contains("hello-raw-log"));

        let _ = std::fs::remove_dir_all(&dir);
    }
}
