// This file was generated by `crates/core/src/bin/generate_types.rs`.

// Do not edit this file manually.

// If you are an AI, and you absolutely have to edit this file, please confirm with the user first.

export type Repo = { id: string, path: string, name: string, display_name: string, setup_script: string | null, cleanup_script: string | null, archive_script: string | null, copy_files: string | null, parallel_setup_script: boolean, dev_server_script: string | null, default_target_branch: string | null, default_working_dir: string | null, created_at: Date, updated_at: Date, };

export type Project = { id: string, name: string, default_agent_working_dir: string | null, remote_project_id: string | null, created_at: Date, updated_at: Date, };

export type UpdateRepo = { display_name?: string | null, setup_script?: string | null, cleanup_script?: string | null, archive_script?: string | null, copy_files?: string | null, parallel_setup_script?: boolean | null, dev_server_script?: string | null, default_target_branch?: string | null, default_working_dir?: string | null, };

export type SearchResult = { path: string, is_file: boolean, match_type: SearchMatchType, 
/**
 * Ranking score based on git history (higher = more recently/frequently edited)
 */
score: bigint, };

export type SearchMatchType = "FileName" | "DirectoryName" | "FullPath";

export type WorkspaceRepo = { id: string, workspace_id: string, repo_id: string, target_branch: string, created_at: Date, updated_at: Date, };

export type CreateWorkspaceRepo = { repo_id: string, target_branch: string, };

export type RepoWithTargetBranch = { target_branch: string, id: string, path: string, name: string, display_name: string, setup_script: string | null, cleanup_script: string | null, archive_script: string | null, copy_files: string | null, parallel_setup_script: boolean, dev_server_script: string | null, default_target_branch: string | null, default_working_dir: string | null, created_at: Date, updated_at: Date, };

export type Tag = { id: string, tag_name: string, content: string, created_at: string, updated_at: string, };

export type CreateTag = { tag_name: string, content: string, };

export type UpdateTag = { tag_name: string | null, content: string | null, };

export type BrowserSession = { id: string, workspace_id: string, host_id: string, profile: string | null, status: BrowserSessionDbStatus, current_url: string | null, 
/**
 * OS process group id of the spawned Chromium process group, used to
 * clean up orphaned process groups after a server crash. Not
 * meaningful across machines.
 */
pgid: bigint | null, created_at: string, updated_at: string, closed_at: string | null, expires_at: string | null, };

export enum BrowserSessionDbStatus { starting = "starting", running = "running", closed = "closed", failed = "failed" }

export type CreateBrowserSession = { workspace_id: string, profile: string | null, };

export type BrowserControlTransition = { id: string, browser_session_id: string, generation: bigint, controller_type: string, execution_id: string | null, user_id: string | null, connection_id: string | null, reason: string, created_at: string, };

export type BrowserController = { "type": "none" } | { "type": "agent", execution_id: string, } | { "type": "human", user_id: string, connection_id: string, };

export type ControlTransitionReason = "acquire" | "release" | "transfer" | "takeover" | "expired" | "disconnected" | "execution_completed" | "closed";

export type BrowserControlState = { controller: BrowserController, generation: number, lease_expires_at: string | null, };

export enum BrowserSessionStatus { starting = "starting", running = "running", closed = "closed", failed = "failed" }

export type BrowserSessionLiveState = { session_id: string, workspace_id: string, status: BrowserSessionStatus, current_url: string | null, page_title: string | null, control: BrowserControlState, expires_at: string | null, };

export type MouseButton = "left" | "middle" | "right";

export type BrowserAction = { "type": "navigate", url: string, } | { "type": "back" } | { "type": "forward" } | { "type": "reload" } | { "type": "click", x: number, y: number, button: MouseButton | null, } | { "type": "mouse_move", x: number, y: number, } | { "type": "type", text: string, } | { "type": "key", key: string, modifiers: Array<string> | null, } | { "type": "set_viewport", width: number, height: number, } | { "type": "evaluate", expression: string, };

export type BrowserActionResult = { command_id: string, generation: number, 
/**
 * Present for Evaluate.
 */
value: JsonValue | null, current_url: string | null, };

export type BrowserPageInfo = { url: string | null, title: string | null, console_tail: Array<string>, };

export type BrowserSessionError = { "code": "CONTROL_CONFLICT", controller: BrowserController, generation: number, } | { "code": "STALE_GENERATION", controller: BrowserController, generation: number, } | { "code": "CONTROL_LOST", controller: BrowserController, generation: number, } | { "code": "NO_RUNNING_EXECUTION" } | { "code": "SESSION_CLOSED" } | { "code": "NOT_FOUND" } | { "code": "BROWSER_UNAVAILABLE", message: string, } | { "code": "CAPABILITY_DENIED", capability: string, } | { "code": "DRIVER_ERROR", message: string, } | { "code": "TIMEOUT" } | { "code": "STORAGE_ERROR", message: string, } | { "code": "EXECUTION_NOT_IN_WORKSPACE" };

export type BrowserSessionWithState = { session: BrowserSession, live: BrowserSessionLiveState | null, };

export type BrowserSessionListQuery = { workspace_id: string, include_closed: boolean, };

export type BrowserPrincipalKind = "human" | "agent";

export type BrowserAcquireRequest = { as: BrowserPrincipalKind, execution_id: string | null, take_from_agent: boolean, force: boolean, expected_generation: number | null, };

export type BrowserReleaseRequest = { as: BrowserPrincipalKind, execution_id: string | null, expected_generation: number | null, };

export type BrowserTransferTargetRequest = { "type": "none" } | { "type": "agent", execution_id: string, };

export type BrowserTransferRequest = { as: BrowserPrincipalKind, execution_id: string | null, expected_generation: number, target: BrowserTransferTargetRequest, };

export type BrowserActionRequest = { as: BrowserPrincipalKind, execution_id: string | null, command_id: string, expected_generation: number | null, action: BrowserAction, 
/**
 * Agent action tools may auto-acquire an uncontrolled session; they can
 * never displace a live controller.
 */
auto_acquire: boolean, };

export type BrowserCloseQuery = { force: boolean, };

export type BrowserWsServerMessage = { "type": "ready", connection_id: string, state: BrowserSessionLiveState, } | { "type": "state", state: BrowserSessionLiveState, } | { "type": "frame", seq: number, width: number, height: number, } | { "type": "command_result", command_id: string | null, ok: boolean, result: BrowserActionResult | null, control: BrowserControlState | null, error: BrowserSessionError | null, };

export type BrowserWsClientMessage = { "type": "input", command_id: string, expected_generation: number | null, action: BrowserAction, } | { "type": "acquire", take_from_agent: boolean, force: boolean, expected_generation: number | null, } | { "type": "release", expected_generation: number | null, } | { "type": "transfer", expected_generation: number, target: BrowserTransferTargetRequest, };

export type DraftFollowUpData = { message: string, executor_config: ExecutorConfig, };

export type DraftWorkspaceData = { message: string, repos: Array<DraftWorkspaceRepo>, executor_config: ExecutorConfig | null, linked_issue: DraftWorkspaceLinkedIssue | null, attachments: Array<DraftWorkspaceAttachment>, };

export type DraftWorkspaceAttachment = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, };

export type DraftWorkspaceLinkedIssue = { issue_id: string, simple_id: string, title: string, remote_project_id: string, };

export type DraftWorkspaceRepo = { repo_id: string, target_branch: string, };

export type DraftIssueData = { title: string, description: string | null, status_id: string, 
/**
 * Stored as the string value of IssuePriority (e.g. "urgent", "high", "medium", "low")
 */
priority: string | null, assignee_ids: Array<string>, tag_ids: Array<string>, create_draft_workspace: boolean, 
/**
 * The project this draft belongs to
 */
project_id: string, 
/**
 * Parent issue ID if creating a sub-issue
 */
parent_issue_id: string | null, };

export type PreviewSettingsData = { url: string, screen_size: string | null, responsive_width: number | null, responsive_height: number | null, };

export type WorkspaceNotesData = { content: string, };

export type WorkspacePanelStateData = { right_main_panel_mode: string | null, is_left_main_panel_visible: boolean, };

export type WorkspacePrFilterData = "all" | "has_pr" | "no_pr";

export type WorkspaceSortByData = "updated_at" | "created_at";

export type WorkspaceSortOrderData = "asc" | "desc";

export type WorkspaceFilterStateData = { project_ids: Array<string>, pr_filter: WorkspacePrFilterData, };

export type WorkspaceSortStateData = { sort_by: WorkspaceSortByData, sort_order: WorkspaceSortOrderData, };

export type UiPreferencesData = { 
/**
 * Preferred repo actions per repo
 */
repo_actions: { [key in string]?: string }, 
/**
 * Expanded/collapsed state for UI sections
 */
expanded: { [key in string]?: boolean }, 
/**
 * Context bar position
 */
context_bar_position: string | null, 
/**
 * Pane sizes
 */
pane_sizes: { [key in string]?: JsonValue }, 
/**
 * Collapsed paths per workspace in file tree
 */
collapsed_paths: { [key in string]?: Array<string> }, 
/**
 * Preferred file-search repo
 */
file_search_repo_id: string | null, 
/**
 * Global left sidebar visibility
 */
is_left_sidebar_visible: boolean | null, 
/**
 * Global right sidebar visibility
 */
is_right_sidebar_visible: boolean | null, 
/**
 * Global terminal visibility
 */
is_terminal_visible: boolean | null, 
/**
 * Workspace-specific panel states
 */
workspace_panel_states: { [key in string]?: WorkspacePanelStateData }, 
/**
 * Workspace sidebar filter preferences
 */
workspace_filters: WorkspaceFilterStateData, 
/**
 * Workspace sidebar sort preferences
 */
workspace_sort: WorkspaceSortStateData, 
/**
 * Last selected organization ID
 */
selected_org_id: string | null, 
/**
 * Last selected project ID
 */
selected_project_id: string | null, 
/**
 * Default setting for creating a draft workspace from new issues
 */
create_draft_workspace_by_default: boolean | null, 
/**
 * Kanban project view selections (active view per project)
 */
kanban_project_view_selections: { [key in string]?: JsonValue }, 
/**
 * Kanban project view preferences (filters, toggles per project per view)
 */
kanban_project_view_preferences: { [key in string]?: JsonValue }, 
/**
 * Kanban board view mode (kanban | list | slim)
 */
kanban_view_mode: string | null, 
/**
 * Selected hidden-status tab, stored by status name (not id, since status
 * ids are per-project and this preference is global)
 */
list_view_status_filter_name: string | null, };

export type ProjectRepoDefaultsData = { repos: Array<DraftWorkspaceRepo>, };

export type ScratchPayload = { "type": "DRAFT_TASK", "data": string } | { "type": "DRAFT_FOLLOW_UP", "data": DraftFollowUpData } | { "type": "DRAFT_WORKSPACE", "data": DraftWorkspaceData } | { "type": "DRAFT_ISSUE", "data": DraftIssueData } | { "type": "PREVIEW_SETTINGS", "data": PreviewSettingsData } | { "type": "WORKSPACE_NOTES", "data": WorkspaceNotesData } | { "type": "UI_PREFERENCES", "data": UiPreferencesData } | { "type": "PROJECT_REPO_DEFAULTS", "data": ProjectRepoDefaultsData };

export enum ScratchType { DRAFT_TASK = "DRAFT_TASK", DRAFT_FOLLOW_UP = "DRAFT_FOLLOW_UP", DRAFT_WORKSPACE = "DRAFT_WORKSPACE", DRAFT_ISSUE = "DRAFT_ISSUE", PREVIEW_SETTINGS = "PREVIEW_SETTINGS", WORKSPACE_NOTES = "WORKSPACE_NOTES", UI_PREFERENCES = "UI_PREFERENCES", PROJECT_REPO_DEFAULTS = "PROJECT_REPO_DEFAULTS" }

export type Scratch = { id: string, payload: ScratchPayload, created_at: string, updated_at: string, };

export type CreateScratch = { payload: ScratchPayload, };

export type UpdateScratch = { payload: ScratchPayload, };

export type Workspace = { id: string, task_id: string | null, container_ref: string | null, branch: string, setup_completed_at: string | null, created_at: string, updated_at: string, archived: boolean, pinned: boolean, name: string | null, worktree_deleted: boolean, 
/**
 * Which numbered `## Pipeline` stage the execution agent last reported
 * itself as starting (1-based), detected from a `VK-PIPELINE-STAGE: N`
 * marker in the execution's raw log stream. `None` when no coding-agent
 * execution has reported a stage yet for the current run.
 */
current_pipeline_stage: bigint | null, 
/**
 * SpecKit feature key: the workspace's branch, captured verbatim at first
 * SpecKit provisioning. Artifacts live under `specs/<feature_key>/` in the
 * spec-host repo. Once set it is never re-derived.
 */
speckit_feature_key: string | null, 
/**
 * Which repo worktree hosts `specs/` + `.specify/` for this workspace's
 * SpecKit artifacts. Persisted at first provisioning.
 */
speckit_host_repo_id: string | null, };

export type WorkspaceWithStatus = { is_running: boolean, is_errored: boolean, id: string, task_id: string | null, container_ref: string | null, branch: string, setup_completed_at: string | null, created_at: string, updated_at: string, archived: boolean, pinned: boolean, name: string | null, worktree_deleted: boolean, 
/**
 * Which numbered `## Pipeline` stage the execution agent last reported
 * itself as starting (1-based), detected from a `VK-PIPELINE-STAGE: N`
 * marker in the execution's raw log stream. `None` when no coding-agent
 * execution has reported a stage yet for the current run.
 */
current_pipeline_stage: bigint | null, 
/**
 * SpecKit feature key: the workspace's branch, captured verbatim at first
 * SpecKit provisioning. Artifacts live under `specs/<feature_key>/` in the
 * spec-host repo. Once set it is never re-derived.
 */
speckit_feature_key: string | null, 
/**
 * Which repo worktree hosts `specs/` + `.specify/` for this workspace's
 * SpecKit artifacts. Persisted at first provisioning.
 */
speckit_host_repo_id: string | null, };

export type Session = { id: string, workspace_id: string, name: string | null, executor: string | null, agent_working_dir: string | null, created_at: string, updated_at: string, };

export type ExecutionProcess = { id: string, session_id: string, run_reason: ExecutionProcessRunReason, executor_action: ExecutorAction, status: ExecutionProcessStatus, exit_code: bigint | null, 
/**
 * OS process group id of the spawned child, used to clean up orphaned
 * process groups after a server crash. Not meaningful across machines.
 */
pgid: bigint | null, 
/**
 * dropped: true if this process is excluded from the current
 * history view (due to restore/trimming). Hidden from logs/timeline;
 * still listed in the Processes tab.
 */
dropped: boolean, started_at: string, completed_at: string | null, created_at: string, updated_at: string, };

export enum ExecutionProcessStatus { running = "running", completed = "completed", failed = "failed", killed = "killed", interrupted = "interrupted" }

export type ExecutionProcessRunReason = "setupscript" | "cleanupscript" | "archivescript" | "codingagent" | "devserver" | "backgroundhelper";

export type ExecutionProcessRepoState = { id: string, execution_process_id: string, repo_id: string, before_head_commit: string | null, after_head_commit: string | null, merge_commit: string | null, created_at: Date, updated_at: Date, };

export type Merge = { "type": "direct" } & DirectMerge | { "type": "pr" } & PrMerge;

export type DirectMerge = { id: string, workspace_id: string, repo_id: string, merge_commit: string, target_branch_name: string, created_at: string, };

export type PrMerge = { id: string, workspace_id: string, repo_id: string, created_at: string, target_branch_name: string, pr_info: PullRequestInfo, };

export type MergeStatus = "open" | "merged" | "closed" | "unknown";

export type PullRequestInfo = { number: bigint, url: string, status: MergeStatus, merged_at: string | null, merge_commit_sha: string | null, };

export type ApprovalInfo = { approval_id: string, tool_name: string, execution_process_id: string, is_question: boolean, created_at: string, timeout_at: string, };

export type ApprovalStatus = { "status": "pending" } | { "status": "approved" } | { "status": "denied", reason?: string, } | { "status": "timed_out" };

export type QuestionAnswer = { question: string, answer: Array<string>, };

export type QuestionStatus = { "status": "answered", answers: Array<QuestionAnswer>, } | { "status": "timed_out" };

export type ApprovalOutcome = { "status": "approved" } | { "status": "denied", reason?: string, } | { "status": "answered", answers: Array<QuestionAnswer>, } | { "status": "timed_out" };

export type ApprovalResponse = { execution_process_id: string, status: ApprovalOutcome, };

export type Diff = { change: DiffChangeKind, oldPath: string | null, newPath: string | null, oldContent: string | null, newContent: string | null, 
/**
 * True when file contents are intentionally omitted (e.g., too large)
 */
contentOmitted: boolean, 
/**
 * Optional precomputed stats for omitted content
 */
additions: number | null, deletions: number | null, repoId: string | null, };

export type DiffChangeKind = "added" | "deleted" | "modified" | "renamed" | "copied" | "permissionChange";

export type ApiResponse<T, E = T> = { success: boolean, data: T | null, error_data: E | null, message: string | null, };

export type LoginStatus = { "status": "loggedout" } | { "status": "loggedin", profile: ProfileResponse | null, };

export type ProfileResponse = { user_id: string, username: string | null, email: string, providers: Array<ProviderProfile>, };

export type ProviderProfile = { provider: string, username: string | null, display_name: string | null, email: string | null, avatar_url: string | null, };

export type StatusResponse = { logged_in: boolean, profile: ProfileResponse | null, degraded: boolean | null, single_user_mode: boolean | null, };

export enum MemberRole { ADMIN = "ADMIN", MEMBER = "MEMBER" }

export enum InvitationStatus { PENDING = "PENDING", ACCEPTED = "ACCEPTED", DECLINED = "DECLINED", EXPIRED = "EXPIRED" }

export type Organization = { id: string, name: string, slug: string, is_personal: boolean, issue_prefix: string, created_at: string, updated_at: string, };

export type OrganizationWithRole = { id: string, name: string, slug: string, is_personal: boolean, issue_prefix: string, created_at: string, updated_at: string, user_role: MemberRole, };

export type ListOrganizationsResponse = { organizations: Array<OrganizationWithRole>, };

export type GetOrganizationResponse = { organization: Organization, user_role: string, };

export type CreateOrganizationRequest = { name: string, slug: string, };

export type CreateOrganizationResponse = { organization: OrganizationWithRole, };

export type UpdateOrganizationRequest = { name: string, };

export type Invitation = { id: string, organization_id: string, invited_by_user_id: string | null, email: string, role: MemberRole, status: InvitationStatus, token: string, created_at: string, expires_at: string, };

export type CreateInvitationRequest = { email: string, role: MemberRole, };

export type CreateInvitationResponse = { invitation: Invitation, };

export type ListInvitationsResponse = { invitations: Array<Invitation>, };

export type GetInvitationResponse = { id: string, organization_slug: string, role: MemberRole, expires_at: string, };

export type AcceptInvitationResponse = { organization_id: string, organization_slug: string, role: MemberRole, };

export type RevokeInvitationRequest = { invitation_id: string, };

export type OrganizationMemberInfo = { user_id: string, role: MemberRole, joined_at: string, };

export type OrganizationMemberWithProfile = { user_id: string, role: MemberRole, joined_at: string, first_name: string | null, last_name: string | null, username: string | null, email: string | null, avatar_url: string | null, };

export type ListMembersResponse = { members: Array<OrganizationMemberWithProfile>, };

export type UpdateMemberRoleRequest = { role: MemberRole, };

export type UpdateMemberRoleResponse = { user_id: string, role: MemberRole, };

export type OrganizationEnvVar = { id: string, organization_id: string, name: string, created_at: string, updated_at: string, };

export type ListOrganizationEnvVarsResponse = { env_vars: Array<OrganizationEnvVar>, };

export type CreateOrganizationEnvVarRequest = { name: string, value: string, };

export type CreateOrganizationEnvVarResponse = { env_var: OrganizationEnvVar, };

export type UpdateOrganizationEnvVarRequest = { value: string, };

export type UpdateOrganizationEnvVarResponse = { env_var: OrganizationEnvVar, };

export type RegisterRepoRequest = { path: string, display_name: string | null, };

export type InitRepoRequest = { parent_path: string, folder_name: string, };

export type TagSearchParams = { search: string | null, };

export type TokenResponse = { access_token: string, expires_at: string | null, };

export type UserSystemInfo = { version: string, config: Config, machine_id: string, login_status: LoginStatus, remote_auth_degraded: string | null, environment: Environment, 
/**
 * Capabilities supported per executor (e.g., { "CLAUDE_CODE": ["SESSION_FORK"] })
 */
capabilities: { [key in string]?: Array<BaseAgentCapability> }, shared_api_base: string | null, preview_proxy_port: number | null, single_user_mode: boolean, 
/**
 * Whether the local deployment can accept attachment uploads.
 * Always true today (filesystem-backed); kept as a capability flag so
 * the frontend can render a unified "Attachments" status alongside the
 * remote deployment's `attachments_enabled`.
 */
attachments_enabled: boolean, executors: { [key in BaseCodingAgent]?: ExecutorProfile }, };

export type Environment = { os_type: string, os_version: string, os_architecture: string, bitness: string, };

export type McpServerQuery = { executor: BaseCodingAgent, };

export type UpdateMcpServersBody = { servers: { [key in string]?: JsonValue }, };

export type GetMcpServerResponse = { mcp_config: McpConfig, config_path: string, };

export type TestMcpServersBody = { 
/**
 * When present and non-empty, only these servers are tested; otherwise all
 * of the agent's configured servers are tested.
 */
servers: Array<string> | null, };

export type SharedMcpProfile = { executor: BaseCodingAgent, display_name: string, supports_mcp: boolean, config_path: string | null, servers_path: Array<string>, read_error: string | null, };

export type McpTransportKind = "stdio" | "http" | "sse" | "unknown";

export type McpServerDefinition = { transport: McpTransportKind, value: JsonValue, representable_in_form: boolean, };

export type NativeMcpSource = { executor: BaseCodingAgent, config_path: string, server_name: string, entry: JsonValue, normalized_fingerprint: string | null, };

export type SharedMcpAssignment = { executor: BaseCodingAgent, native_name: string, native_entry: JsonValue | null, has_credentials: boolean, representable: boolean, incompatibility_reason: string | null, };

export type SharedMcpSourceKind = "reconciled" | "single_profile" | "new" | "custom";

export type SharedMcpAuthMode = "shared_gateway" | "agent_native" | "explicit_header" | "none";

export type SharedMcpCompatibility = { executor: BaseCodingAgent, compatible: boolean, reason: string | null, };

export type SharedMcpServer = { name: string, definition: McpServerDefinition, assignments: Array<SharedMcpAssignment>, source_kind: SharedMcpSourceKind, native_sources: Array<NativeMcpSource>, compatibility: Array<SharedMcpCompatibility>, auth_mode: SharedMcpAuthMode, gateway_status: string | null, };

export type SharedMcpConflictVariant = { variant_id: string, definition: McpServerDefinition, assignments: Array<SharedMcpAssignment>, native_sources: Array<NativeMcpSource>, };

export type SharedMcpConflict = { name: string, variants: Array<SharedMcpConflictVariant>, message: string, };

export type SharedMcpProfileError = { executor: BaseCodingAgent, config_path: string | null, error: string, };

export type SharedMcpReadResponse = { profiles: Array<SharedMcpProfile>, servers: Array<SharedMcpServer>, conflicts: Array<SharedMcpConflict>, preconfigured: JsonValue, read_errors: Array<SharedMcpProfileError>, };

export type SharedMcpServerInput = { name: string, definition: McpServerDefinition, assignments: Array<BaseCodingAgent>, native_overrides: { [key in BaseCodingAgent]?: JsonValue }, };

export type SharedMcpConflictResolution = { name: string, };

export type SharedMcpWriteRequest = { servers: Array<SharedMcpServerInput>, removed_servers: Array<string>, resolved_conflicts: Array<SharedMcpConflictResolution>, };

export type SharedMcpWriteStatus = "success" | "partial_failure" | "failed";

export type SharedMcpProfileWriteStatus = "success" | "skipped" | "failed";

export type SharedMcpProfileWriteOutcome = { executor: BaseCodingAgent, config_path: string | null, status: SharedMcpProfileWriteStatus, affected_servers: Array<string>, message: string | null, error: string | null, };

export type SharedMcpWriteResponse = { status: SharedMcpWriteStatus, outcomes: Array<SharedMcpProfileWriteOutcome>, servers: Array<SharedMcpServer>, conflicts: Array<SharedMcpConflict>, };

export type SharedMcpTestTarget = { server_name: string, executor: BaseCodingAgent, };

export type SharedMcpTestRequest = { targets: Array<SharedMcpTestTarget>, };

export type SharedMcpAssignmentTestResult = { server_name: string, executor: BaseCodingAgent, gateway_status: string | null, upstream_status: string | null, result: McpServerTestResult, };

export type McpServerTestResult = { name: string, 
/**
 * `"stdio" | "http" | "sse" | "unknown"`.
 */
transport: string, status: McpServerTestStatus, latency_ms: bigint | null, tool_count: number | null, server_name: string | null, server_version: string | null, error: string | null, 
/**
 * Raw `WWW-Authenticate` header from an authentication response, when the
 * server sent one (per RFC 9728 it points at the protected-resource
 * metadata needed to start OAuth).
 */
www_authenticate: string | null, };

export type McpServerTestStatus = "ok" | "failed" | "auth_required" | "unsupported";

export type McpAuthStartRequest = { server_name: string, 
/**
 * The `WWW-Authenticate` header a probe captured for this server, if
 * any. Some servers only issue their challenge (and its
 * `resource_metadata` pointer) on the JSON-RPC POST the probe makes —
 * passing it here lets discovery start from it instead of hoping a
 * plain GET re-elicits one.
 */
www_authenticate: string | null, 
/**
 * Register a `http://localhost:<port>` callback instead of deriving it
 * from the request host. Authorization servers with a strict allowlist
 * (Claude/ChatGPT/Codex/Cursor/localhost) reject a public callback; a
 * loopback one is accepted. When the browser can reach that loopback
 * (same machine or an SSH port-forward) the callback completes
 * automatically; otherwise the user pastes the full redirected URL back
 * via `/mcp-auth/complete`.
 */
loopback: boolean, 
/**
 * Store this connection once in the shared local gateway and replace all
 * matching native assignments with the protected loopback endpoint.
 */
shared_gateway: boolean, 
/**
 * Write-only Cloudflare Access service-token values used for discovery
 * and upstream gateway requests. Never returned by a read API.
 */
cf_access_client_id?: string, cf_access_client_secret?: string, };

export type McpAuthStartResponse = { flow_id: string, authorize_url: string, 
/**
 * True when this flow used a loopback callback, so the frontend knows to
 * offer manual callback-URL entry if the popup can't reach it.
 */
loopback: boolean, };

export type McpAuthCompleteRequest = { flow_id: string, 
/**
 * Full redirect URL the browser landed on, including both `code` and
 * `state` (`http://localhost:…/callback?code=…&state=…`).
 */
code: string, };

export type McpAuthFlowState = "pending" | "completed" | "failed";

export type McpAuthStatusResponse = { status: McpAuthFlowState, error: string | null, };

export type CliToolId = "aws" | "az" | "op" | "gam" | "mgc-beta" | "acli" | "gws" | "graph-powershell-1.0";

export type CliToolAuthState = "authenticated" | "unauthenticated" | "unknown" | "unsupported";

export type HostCopy = { path: string, version: string | null, };

export type AppCopy = { version: string, outdated: boolean, installed_at: string, };

export type CliToolStatus = { id: CliToolId, binary_name: string, display_name: string, description: string, catalog_version: string, supported: boolean, unsupported_reason: string | null, host: HostCopy | null, app: AppCopy | null, docs_url: string, login_supported: boolean, auth_state: CliToolAuthState, auth_message: string | null, };

export type AwsSsoProfile = { name: string, sso_start_url: string, sso_region: string, sso_account_id: string, sso_role_name: string, region: string | null, output: string | null, };

export type AwsAuthStatus = { "status": "authenticated", identity: string, } | { "status": "unauthenticated" } | { "status": "unknown", message: string, } | { "status": "cli_missing" };

export type AwsSsoAuthScope = { 
/**
 * Namespaced stable key (`session:<name>` or `start-url:<url>`).
 */
key: string, 
/**
 * Named session, or the start URL for a legacy inline profile.
 */
label: string, 
/**
 * Present for modern profiles backed by `[sso-session <name>]`.
 */
session_name: string | null, };

export type AwsSsoProfileStatus = { profile: AwsSsoProfile, auth: AwsAuthStatus, 
/**
 * False for `[default]` (list/sign-in only): VK never rewrites it.
 */
editable: boolean, 
/**
 * Shared AWS CLI token-cache identity used to group authentication UI.
 */
auth_scope: AwsSsoAuthScope, };

export type AwsSsoSession = { name: string, sso_start_url: string, sso_region: string, };

export type AwsSsoAccount = { account_id: string, account_name: string, roles: Array<string>, };

export type AwsProfileImportCandidate = { name: string, sso_account_id: string, sso_role_name: string, overwrite: boolean, };

export type AwsProfileImportRequest = { session_name: string, region: string, output: string | null, profiles: Array<AwsProfileImportCandidate>, };

export type AwsProfileImportResult = { created: Array<string>, updated: Array<string>, };

export type CheckEditorAvailabilityQuery = { editor_type: EditorType, };

export type CheckEditorAvailabilityResponse = { available: boolean, };

export type CheckAgentAvailabilityQuery = { executor: BaseCodingAgent, };

export type AgentPresetOptionsQuery = { executor: BaseCodingAgent, variant: string | null, };

export type CurrentUserResponse = { user_id: string, };

export type StartSpake2EnrollmentRequest = { enrollment_code: string, client_message_b64: string, };

export type FinishSpake2EnrollmentRequest = { enrollment_id: string, client_id: string, client_name: string, client_browser: string, client_os: string, client_device: string, public_key_b64: string, client_proof_b64: string, };

export type StartSpake2EnrollmentResponse = { enrollment_id: string, server_message_b64: string, };

export type FinishSpake2EnrollmentResponse = { signing_session_id: string, server_public_key_b64: string, server_proof_b64: string, };

export type RelayPairedClient = { client_id: string, client_name: string, client_browser: string, client_os: string, client_device: string, };

export type ListRelayPairedClientsResponse = { clients: Array<RelayPairedClient>, };

export type RemoveRelayPairedClientResponse = { removed: boolean, };

export type RefreshRelaySigningSessionRequest = { client_id: string, timestamp: bigint, nonce: string, signature_b64: string, };

export type RefreshRelaySigningSessionResponse = { signing_session_id: string, };

export type CreateFollowUpAttempt = { prompt: string, executor_config: ExecutorConfig, retry_process_id: string | null, force_when_dirty: boolean | null, perform_git_reset: boolean | null, };

export type ResetProcessRequest = { process_id: string, force_when_dirty: boolean | null, perform_git_reset: boolean | null, };

export type ChangeTargetBranchRequest = { repo_id: string, new_target_branch: string, };

export type ChangeTargetBranchResponse = { repo_id: string, new_target_branch: string, status: [number, number], };

export type AddWorkspaceRepoRequest = { repo_id: string, target_branch: string, };

export type AddWorkspaceRepoResponse = { workspace: Workspace, repo: RepoWithTargetBranch, };

export type MergeWorkspaceRequest = { repo_id: string, };

export type PushWorkspaceRequest = { repo_id: string, };

export type RenameBranchRequest = { new_branch_name: string, };

export type RenameBranchResponse = { branch: string, };

export type StartReviewRequest = { executor_config: ExecutorConfig, additional_prompt: string | null, use_all_workspace_commits: boolean, };

export type ReviewError = { "type": "process_already_running" };

export type OpenEditorRequest = { editor_type: string | null, file_path: string | null, };

export type OpenEditorResponse = { url: string | null, };

export type OpenRemoteEditorResponse = { url: string, local_port: number, ssh_alias: string, };

export type OpenRemoteWorkspaceInEditorRequest = { host_id: string, workspace_id: string, editor_type: string | null, file_path: string | null, };

export type PairRelayHostRequest = { host_id: string, host_name: string, enrollment_code: string, };

export type PairRelayHostResponse = { paired: boolean, };

export type RelayPairedHost = { host_id: string, host_name: string | null, paired_at: string | null, };

export type ListRelayPairedHostsResponse = { hosts: Array<RelayPairedHost>, };

export type RemoveRelayPairedHostResponse = { removed: boolean, };

export type CreateWorkspaceApiRequest = { name: string | null, };

export type LinkedIssueInfo = { remote_project_id: string, issue_id: string, };

export type CreatePrApiRequest = { title: string, body: string | null, target_branch: string | null, draft: boolean | null, repo_id: string, auto_generate_description: boolean, };

export type AttachmentResponse = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, created_at: string, updated_at: string, };

export type AttachmentMetadata = { exists: boolean, file_name: string | null, path: string | null, size_bytes: bigint | null, format: string | null, proxy_url: string | null, };

export type WorkspaceRepoInput = { repo_id: string, target_branch: string, };

export type RunAgentSetupRequest = { executor_profile_id: ExecutorProfileId, };

export type RunAgentSetupResponse = Record<string, never>;

export type GhCliSetupError = "BREW_MISSING" | "SETUP_HELPER_NOT_SUPPORTED" | { "OTHER": { message: string, } };

export type RebaseWorkspaceRequest = { repo_id: string, old_base_branch: string | null, new_base_branch: string | null, };

export type ContinueRebaseRequest = { repo_id: string, };

export type AbortConflictsRequest = { repo_id: string, };

export type GitOperationError = { "type": "merge_conflicts", message: string, op: ConflictOp, conflicted_files: Array<string>, target_branch: string, } | { "type": "rebase_in_progress" };

export type PushError = { "type": "force_push_required" };

export type PrError = { "type": "cli_not_installed", provider: ProviderKind, } | { "type": "cli_not_logged_in", provider: ProviderKind, } | { "type": "git_cli_not_logged_in" } | { "type": "git_cli_not_installed" } | { "type": "target_branch_not_found", branch: string, } | { "type": "unsupported_provider" };

export type RunScriptError = { "type": "no_script_configured" } | { "type": "process_already_running" };

export type StartBackgroundHelperError = { "type": "empty_script" } | { "type": "invalid_working_dir" } | { "type": "too_many_helpers" };

export type StartBackgroundHelperRequest = { 
/**
 * Bash script to run as the helper (e.g. a watcher or tunnel).
 */
script: string, 
/**
 * Optional path to run the script in, relative to the workspace root.
 */
working_dir: string | null, };

export type AssociateWorkspaceAttachmentsRequest = { attachment_ids: Array<string>, };

export type ImportIssueAttachmentsRequest = { issue_id: string, };

export type ImportIssueAttachmentsResponse = { attachment_ids: Array<string>, };

export type AttachPrResponse = { pr_attached: boolean, pr_url: string | null, pr_number: bigint | null, pr_status: MergeStatus | null, };

export type AttachExistingPrRequest = { repo_id: string, };

export type PrCommentsResponse = { comments: Array<UnifiedPrComment>, };

export type GetPrCommentsError = { "type": "no_pr_attached" } | { "type": "cli_not_installed", provider: ProviderKind, } | { "type": "cli_not_logged_in", provider: ProviderKind, };

export type GetPrCommentsQuery = { repo_id: string, };

export type CreateAndStartWorkspaceRequest = { name: string | null, repos: Array<WorkspaceRepoInput>, linked_issue: LinkedIssueInfo | null, executor_config: ExecutorConfig, prompt: string, attachment_ids: Array<string> | null, };

export type CreateAndStartWorkspaceResponse = { workspace: Workspace, execution_process: ExecutionProcess, };

export type UnifiedPrComment = { "comment_type": "general", id: string, author: string, author_association: string | null, body: string, created_at: string, url: string | null, } | { "comment_type": "review", id: bigint, author: string, author_association: string | null, body: string, created_at: string, url: string | null, path: string, line: bigint | null, side: string | null, diff_hunk: string | null, };

export type ProviderKind = "git_hub" | "azure_dev_ops" | "unknown";

export type PullRequestDetail = { number: bigint, url: string, status: MergeStatus, merged_at: string | null, merge_commit_sha: string | null, title: string, base_branch: string, head_branch: string, };

export type GitRemote = { name: string, url: string, };

export type ListPrsError = { "type": "cli_not_installed", provider: ProviderKind, } | { "type": "auth_failed", message: string, } | { "type": "unsupported_provider" };

export type LinkPrToIssueRequest = { pr_url: string, pr_number: number, base_branch: string, };

export type CreateWorkspaceFromPrBody = { repo_id: string, pr_number: bigint, pr_title: string, pr_url: string, head_branch: string, base_branch: string, run_setup: boolean, remote_name: string | null, };

export type CreateWorkspaceFromPrResponse = { workspace: Workspace, };

export type CreateFromPrError = { "type": "pr_not_found" } | { "type": "branch_fetch_failed", message: string, } | { "type": "cli_not_installed", provider: ProviderKind, } | { "type": "auth_failed", message: string, } | { "type": "unsupported_provider" };

export type RepoBranchStatus = { repo_id: string, repo_name: string, commits_behind: number | null, commits_ahead: number | null, has_uncommitted_changes: boolean | null, head_oid: string | null, uncommitted_count: number | null, untracked_count: number | null, target_branch_name: string, remote_commits_behind: number | null, remote_commits_ahead: number | null, merges: Array<Merge>, is_rebase_in_progress: boolean, conflict_op: ConflictOp | null, conflicted_files: Array<string>, is_target_remote: boolean, };

export type UpdateWorkspace = { archived: boolean | null, pinned: boolean | null, name: string | null, };

export type UpdateSession = { name: string | null, };

export type WorkspaceSummaryRequest = { archived: boolean, };

export type WorkspaceSummary = { workspace_id: string, 
/**
 * Session ID of the latest execution process
 */
latest_session_id: string | null, 
/**
 * Is a tool approval currently pending?
 */
has_pending_approval: boolean, 
/**
 * Number of files with changes
 */
files_changed: number | null, 
/**
 * Total lines added across all files
 */
lines_added: number | null, 
/**
 * Total lines removed across all files
 */
lines_removed: number | null, 
/**
 * When the latest execution process completed
 */
latest_process_completed_at?: string, 
/**
 * Status of the latest execution process
 */
latest_process_status: ExecutionProcessStatus | null, 
/**
 * Is a dev server currently running?
 */
has_running_dev_server: boolean, 
/**
 * Does this workspace have unseen coding agent turns?
 */
has_unseen_turns: boolean, 
/**
 * PR status for this workspace (if any PR exists)
 */
pr_status: MergeStatus | null, 
/**
 * PR number for this workspace (if any PR exists)
 */
pr_number: bigint | null, 
/**
 * PR URL for this workspace (if any PR exists)
 */
pr_url: string | null, };

export type WorkspaceSummaryResponse = { summaries: Array<WorkspaceSummary>, };

export type DiffStats = { files_changed: number, lines_added: number, lines_removed: number, };

export type DirectoryEntry = { name: string, path: string, is_directory: boolean, is_git_repo: boolean, last_modified: bigint | null, };

export type DirectoryListResponse = { entries: Array<DirectoryEntry>, current_path: string, };

export type SearchMode = "taskform" | "settings";

export type Config = { config_version: string, theme: ThemeMode, executor_profile: ExecutorProfileId, disclaimer_acknowledged: boolean, onboarding_acknowledged: boolean, remote_onboarding_acknowledged: boolean, notifications: NotificationConfig, editor: EditorConfig, github: GitHubConfig, analytics_enabled: boolean, workspace_dir: string | null, last_app_version: string | null, show_release_notes: boolean, language: UiLanguage, git_branch_prefix: string, showcases: ShowcaseState, pr_auto_description_enabled: boolean, pr_auto_description_prompt: string | null, commit_reminder_enabled: boolean, commit_reminder_prompt: string | null, send_message_shortcut: SendMessageShortcut, relay_enabled: boolean, host_nickname: string | null, 
/**
 * Opt-in: auto-resume coding-agent runs interrupted by a server
 * restart. Off by default because it spawns agents (and spends
 * tokens) at boot without a human in the loop.
 */
resume_interrupted_on_startup: boolean, };

export type NotificationConfig = { sound_enabled: boolean, push_enabled: boolean, sound_file: SoundFile, };

export enum ThemeMode { LIGHT = "LIGHT", DARK = "DARK", SYSTEM = "SYSTEM" }

export type EditorConfig = { editor_type: EditorType, custom_command: string | null, remote_ssh_host: string | null, remote_ssh_user: string | null, auto_install_extension: boolean, };

export enum EditorType { VS_CODE = "VS_CODE", VS_CODE_INSIDERS = "VS_CODE_INSIDERS", CURSOR = "CURSOR", WINDSURF = "WINDSURF", INTELLI_J = "INTELLI_J", ZED = "ZED", XCODE = "XCODE", GOOGLE_ANTIGRAVITY = "GOOGLE_ANTIGRAVITY", CUSTOM = "CUSTOM" }

export type EditorOpenError = { "type": "executable_not_found", executable: string, editor_type: EditorType, } | { "type": "invalid_command", details: string, editor_type: EditorType, } | { "type": "launch_failed", executable: string, details: string, editor_type: EditorType, };

export type GitHubConfig = { pat: string | null, oauth_token: string | null, username: string | null, primary_email: string | null, default_pr_base: string | null, };

export enum SoundFile { ABSTRACT_SOUND1 = "ABSTRACT_SOUND1", ABSTRACT_SOUND2 = "ABSTRACT_SOUND2", ABSTRACT_SOUND3 = "ABSTRACT_SOUND3", ABSTRACT_SOUND4 = "ABSTRACT_SOUND4", COW_MOOING = "COW_MOOING", FAHHHHH = "FAHHHHH", PHONE_VIBRATION = "PHONE_VIBRATION", ROOSTER = "ROOSTER" }

export type UiLanguage = "BROWSER" | "EN" | "FR" | "JA" | "ES" | "KO" | "ZH_HANS" | "ZH_HANT";

export type ShowcaseState = { seen_features: Array<string>, };

export type SendMessageShortcut = "ModifierEnter" | "Enter";

export type PipelineStep = { 
/**
 * Stable slug, e.g. "spec".
 */
id: string, 
/**
 * Shown next to the task-create checkbox.
 */
label: string, 
/**
 * Appended as a bullet when the step is ticked.
 */
prompt_fragment: string, 
/**
 * Whether the task checkbox starts ticked.
 */
default_enabled: boolean, 
/**
 * Whether this stage is marked "heavy" (resource-intensive); the UI
 * renders a badge and it starts unticked by convention.
 */
heavy: boolean, };

export type Pipeline = { 
/**
 * Stable slug = the file stem, e.g. "basic".
 */
id: string, 
/**
 * Display name from the file's `name` field.
 */
name: string, 
/**
 * Optional one-line description.
 */
description: string | null, 
/**
 * Ordered stages; this order is authoritative for the composed block.
 */
stages: Array<PipelineStep>, };

export type PipelineParseError = { message: string, line: number | null, column: number | null, };

export type PipelineValidation = { valid: boolean, error: PipelineParseError | null, };

export type PipelineFileStatus = { id: string, name: string, stage_count: number | null, valid: boolean, error: PipelineParseError | null, };

export type PipelineRawBody = { content: string, };

export type PipelineValidateBody = { id: string | null, content: string, };

export type SpecKitStage = "constitution" | "specify" | "clarify" | "plan" | "tasks" | "analyze" | "implement";

export type SpecKitTask = { 
/**
 * Task identifier as written in tasks.md (e.g. "T001"). Falls back to the
 * 1-based ordinal when the source line has no explicit id.
 */
id: string, 
/**
 * Human-readable task description (the text after the id/marker).
 */
description: string, 
/**
 * File paths referenced in the task line, when present.
 */
file_paths: Array<string>, 
/**
 * True when the task is marked `[P]` (safe to run in parallel).
 */
parallelizable: boolean, 
/**
 * Phase / user-story heading the task is grouped under, if any.
 */
phase?: string, 
/**
 * Whether the task's checkbox is ticked (`[x]`).
 */
done: boolean, };

export type SpecKitTaskLayer = { 
/**
 * Task ids that make up this layer.
 */
task_ids: Array<string>, 
/**
 * True when the layer holds more than one task (i.e. real parallelism).
 */
parallel: boolean, };

export type SpecKitTasks = { tasks: Array<SpecKitTask>, 
/**
 * Ordered parallel layers derived from `[P]` markers + task order.
 */
layers: Array<SpecKitTaskLayer>, total: number, completed: number, };

export type SpecKitArtifact = { 
/**
 * Display name / filename (e.g. "spec.md").
 */
name: string, 
/**
 * Path relative to the feature dir (e.g. "contracts/api-spec.json").
 */
relative_path: string, content?: string, exists: boolean, };

export type SpecKitArtifacts = { 
/**
 * Feature dir relative to the *workspace root*, e.g.
 * "backend/specs/vk/webhook-retries" (spec-host repo prefix included).
 */
feature_dir: string, spec: SpecKitArtifact, plan: SpecKitArtifact, tasks: SpecKitArtifact, research: SpecKitArtifact, data_model: SpecKitArtifact, quickstart: SpecKitArtifact, 
/**
 * Contract files under `contracts/` (json / markdown), if any.
 */
contracts: Array<SpecKitArtifact>, };

export type SpecKitUpdateArtifactRequest = { 
/**
 * Path relative to the feature dir (e.g. "spec.md", "contracts/api.json").
 */
relative_path: string, content: string, };

export type SpecKitToggleTaskRequest = { task_id: string, done: boolean, };

export type SpecKitStageArtifact = { stage: SpecKitStage, 
/**
 * The stage's primary artifact, relative to the workspace root.
 */
artifact: string, exists: boolean, };

export type SpecKitTaskStatus = { workspace_id: string, enabled: boolean, 
/**
 * Explains why `enabled` is false, so the frontend can show accurate
 * copy without re-deriving it.
 */
note?: string, 
/**
 * The SpecKit feature key (the workspace branch, verbatim, captured at
 * first provisioning).
 */
feature_key?: string, 
/**
 * Feature dir relative to the workspace root, e.g.
 * "backend/specs/vk/webhook-retries".
 */
feature_dir?: string, 
/**
 * The spec-host repo's dir relative to the workspace root,
 * e.g. "backend" (repo name plus optional default working dir).
 */
host_rel?: string, 
/**
 * True when the workspace has more than one repo (command files then live
 * at the workspace root and every path is repo-qualified).
 */
multi_repo: boolean, 
/**
 * Per-stage artifact presence, in workflow order.
 */
stages: Array<SpecKitStageArtifact>, 
/**
 * Parsed `tasks.md`, when it exists.
 */
tasks?: SpecKitTasks, };

export type GitBranch = { name: string, is_current: boolean, is_remote: boolean, last_commit_date: Date, };

export type QueuedMessage = { 
/**
 * The session this message is queued for
 */
session_id: string, 
/**
 * The follow-up data (message + variant)
 */
data: DraftFollowUpData, 
/**
 * Timestamp when the message was queued
 */
queued_at: string, };

export type QueueStatus = { "status": "empty" } | { "status": "queued", message: QueuedMessage, };

export type ConflictOp = "rebase" | "merge" | "cherry_pick" | "revert";

export type ExecutorAction = { typ: ExecutorActionType, next_action: ExecutorAction | null, };

export type McpConfig = { servers: { [key in string]?: JsonValue }, servers_path: Array<string>, template: JsonValue, preconfigured: JsonValue, is_toml_config: boolean, };

export type McpRefreshStatus = "pending_next_turn" | "refreshed" | "partially_refreshed" | "busy" | "unsupported" | "failed";

export type McpRefreshErrorCategory = "executable_unavailable" | "process_launch_failed" | "initialize_failed" | "authentication_failed" | "capability_list_failed" | "invalid_capability_schema" | "timeout" | "refresh_in_progress" | "active_call" | "unsupported" | "internal";

export type McpRefreshError = { category: McpRefreshErrorCategory, message: string, remediation: string, retryable: boolean, };

export type McpServerRefreshStatus = "ready" | "failed_retained" | "failed_unavailable" | "removed" | "disabled";

export type McpServerRefreshSnapshot = { server_id: string, status: McpServerRefreshStatus, tool_count: number | null, resource_count: number | null, prompt_count: number | null, restart_occurred: boolean | null, error: McpRefreshError | null, };

export type McpRefreshResult = { status: McpRefreshStatus, retryable: boolean, generation: bigint, requested_at: string, last_successful_refresh_at: string | null, servers: Array<McpServerRefreshSnapshot>, error: McpRefreshError | null, };

export type ExecutorActionType = { "type": "CodingAgentInitialRequest" } & CodingAgentInitialRequest | { "type": "CodingAgentFollowUpRequest" } & CodingAgentFollowUpRequest | { "type": "ScriptRequest" } & ScriptRequest | { "type": "ReviewRequest" } & ReviewRequest;

export type ExecutorConfig = { 
/**
 * The executor type (e.g., CLAUDE_CODE, AMP)
 */
executor: BaseCodingAgent, 
/**
 * Optional variant/preset name (e.g., "PLAN", "ROUTER")
 */
variant?: string | null, 
/**
 * Model override (e.g., "anthropic/claude-sonnet-4-20250514")
 */
model_id?: string | null, 
/**
 * Agent mode override
 */
agent_id?: string | null, 
/**
 * Reasoning effort override (e.g., "high", "medium")
 */
reasoning_id?: string | null, 
/**
 * Permission policy override
 */
permission_policy?: PermissionPolicy | null, };

export type ScriptContext = "SetupScript" | "CleanupScript" | "ArchiveScript" | "DevServer" | "ToolInstallScript" | "BackgroundHelper";

export type ScriptRequest = { script: string, language: ScriptRequestLanguage, context: ScriptContext, 
/**
 * Optional relative path to execute the script in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, };

export type ScriptRequestLanguage = "Bash";

export enum BaseCodingAgent { CLAUDE_CODE = "CLAUDE_CODE", AMP = "AMP", GEMINI = "GEMINI", CODEX = "CODEX", OPENCODE = "OPENCODE", CURSOR_AGENT = "CURSOR_AGENT", QWEN_CODE = "QWEN_CODE", COPILOT = "COPILOT", DROID = "DROID", GROK = "GROK" }

export type CodingAgent = { "CLAUDE_CODE": ClaudeCode } | { "AMP": Amp } | { "GEMINI": Gemini } | { "CODEX": Codex } | { "OPENCODE": Opencode } | { "CURSOR_AGENT": CursorAgent } | { "QWEN_CODE": QwenCode } | { "COPILOT": Copilot } | { "DROID": Droid } | { "GROK": Grok };

export type SlashCommandDescription = { 
/**
 * Command name without the leading slash, e.g. `help` for `/help`.
 */
name: string, description?: string | null, };

export type AvailabilityInfo = { "type": "LOGIN_DETECTED", last_auth_timestamp: bigint, } | { "type": "INSTALLATION_FOUND" } | { "type": "NOT_FOUND" };

export type CommandBuilder = { 
/**
 * Base executable command (e.g., "npx -y @anthropic-ai/claude-code@latest")
 */
base: string, 
/**
 * Optional parameters to append to the base command
 */
params: Array<string> | null, };

export type ExecutorProfileId = { 
/**
 * The executor type (e.g., "CLAUDE_CODE", "AMP")
 */
executor: BaseCodingAgent, 
/**
 * Optional variant name (e.g., "PLAN", "ROUTER")
 */
variant: string | null, };

export type ExecutorRecentModels = { 
/**
 * Ordered list of recently used model keys (most recent last).
 */
models?: Array<string>, 
/**
 * Last-used reasoning effort per model
 */
reasoning_by_model?: { [key in string]?: string }, };

export type ExecutorProfile = { recently_used_models?: ExecutorRecentModels | null, } & ({ [key in string]?: { "CLAUDE_CODE": ClaudeCode } | { "AMP": Amp } | { "GEMINI": Gemini } | { "CODEX": Codex } | { "OPENCODE": Opencode } | { "CURSOR_AGENT": CursorAgent } | { "QWEN_CODE": QwenCode } | { "COPILOT": Copilot } | { "DROID": Droid } | { "GROK": Grok } });

export type ExecutorConfigs = { executors: { [key in BaseCodingAgent]?: ExecutorProfile }, };

export enum BaseAgentCapability { SESSION_FORK = "SESSION_FORK", SETUP_HELPER = "SETUP_HELPER", CONTEXT_USAGE = "CONTEXT_USAGE" }

export type ClaudeEffort = "low" | "medium" | "high" | "xhigh" | "max";

export type ClaudeCode = { append_prompt: AppendPrompt, claude_code_router?: boolean | null, plan?: boolean | null, approvals?: boolean | null, model?: string | null, effort?: ClaudeEffort | null, agent?: string | null, dangerously_skip_permissions?: boolean | null, disable_api_key?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Gemini = { append_prompt: AppendPrompt, model?: string | null, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Grok = { append_prompt: AppendPrompt, model?: string | null, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Amp = { append_prompt: AppendPrompt, dangerously_allow_all?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Codex = { append_prompt: AppendPrompt, sandbox?: SandboxMode | null, ask_for_approval?: AskForApproval | null, oss?: boolean | null, model?: string | null, model_reasoning_effort?: ReasoningEffort | null, model_reasoning_summary?: ReasoningSummary | null, model_reasoning_summary_format?: ReasoningSummaryFormat | null, profile?: string | null, base_instructions?: string | null, include_apply_patch_tool?: boolean | null, model_provider?: string | null, compact_prompt?: string | null, developer_instructions?: string | null, plan: boolean, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type SandboxMode = "auto" | "read-only" | "workspace-write" | "danger-full-access";

export type AskForApproval = "unless-trusted" | "on-failure" | "on-request" | "never";

export type ReasoningEffort = "low" | "medium" | "high" | "xhigh" | "max" | "ultra";

export type ReasoningSummary = "auto" | "concise" | "detailed" | "none";

export type ReasoningSummaryFormat = "none" | "experimental";

export type CursorAgent = { append_prompt: AppendPrompt, force?: boolean | null, model?: string | null, reasoning?: string | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Copilot = { append_prompt: AppendPrompt, model?: string | null, allow_all_tools?: boolean | null, allow_tool?: string | null, deny_tool?: string | null, add_dir?: Array<string> | null, disable_mcp_server?: Array<string> | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Opencode = { append_prompt: AppendPrompt, model?: string | null, variant?: string | null, agent?: string | null, 
/**
 * Auto-approve agent actions
 */
auto_approve: boolean, 
/**
 * Enable auto-compaction when the context length approaches the model's context window limit
 */
auto_compact: boolean, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type QwenCode = { append_prompt: AppendPrompt, model?: string | null, agent?: string | null, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Droid = { append_prompt: AppendPrompt, autonomy: Autonomy, model?: string | null, reasoning_effort?: DroidReasoningEffort | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Autonomy = "normal" | "low" | "medium" | "high" | "skip-permissions-unsafe";

export type DroidReasoningEffort = "none" | "dynamic" | "off" | "low" | "medium" | "high";

export type AppendPrompt = string | null;

export type CodingAgentInitialRequest = { prompt: string, 
/**
 * Unified executor identity + overrides
 */
executor_config: ExecutorConfig, 
/**
 * Optional relative path to execute the agent in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, };

export type CodingAgentFollowUpRequest = { prompt: string, session_id: string, reset_to_message_id: string | null, 
/**
 * Unified executor identity + overrides
 */
executor_config: ExecutorConfig, 
/**
 * Optional relative path to execute the agent in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, };

export type ReviewRequest = { 
/**
 * Unified executor identity + overrides
 */
executor_config: ExecutorConfig, context: Array<RepoReviewContext> | null, prompt: string, 
/**
 * Optional session ID to resume an existing session
 */
session_id: string | null, 
/**
 * Optional relative path to execute the agent in (relative to container_ref).
 */
working_dir: string | null, };

export type RepoReviewContext = { repo_id: string, repo_name: string, base_commit: string, };

export type CommandExitStatus = { "type": "exit_code", code: number, } | { "type": "success", success: boolean, };

export type CommandRunResult = { exit_status: CommandExitStatus | null, output: string | null, };

export type CommandCategory = "read" | "search" | "edit" | "fetch" | "other";

export type NormalizedEntry = { timestamp: string | null, entry_type: NormalizedEntryType, content: string, };

export type NormalizedEntryType = { "type": "user_message" } | { "type": "user_feedback", denied_tool: string, } | { "type": "assistant_message" } | { "type": "tool_use", tool_name: string, action_type: ActionType, status: ToolStatus, } | { "type": "system_message" } | { "type": "error_message", error_type: NormalizedEntryError, } | { "type": "thinking" } | { "type": "loading" } | { "type": "next_action", failed: boolean, execution_processes: number, needs_setup: boolean, } | { "type": "token_usage_info" } & TokenUsageInfo | { "type": "user_answered_questions", answers: Array<AnsweredQuestion>, };

export type TokenUsageInfo = { total_tokens: number, model_context_window: number, };

export type FileChange = { "action": "write", content: string, } | { "action": "delete" } | { "action": "rename", new_path: string, } | { "action": "edit", 
/**
 * Unified diff containing file header and hunks.
 */
unified_diff: string, 
/**
 * Whether line number in the hunks are reliable.
 */
has_line_numbers: boolean, };

export type ActionType = { "action": "file_read", path: string, } | { "action": "file_edit", path: string, changes: Array<FileChange>, } | { "action": "command_run", command: string, result: CommandRunResult | null, category: CommandCategory, } | { "action": "search", query: string, } | { "action": "web_fetch", url: string, } | { "action": "tool", tool_name: string, arguments: JsonValue | null, result: ToolResult | null, } | { "action": "task_create", description: string, subagent_type: string | null, result: ToolResult | null, } | { "action": "plan_presentation", plan: string, } | { "action": "todo_management", todos: Array<TodoItem>, operation: string, } | { "action": "ask_user_question", questions: Array<AskUserQuestionItem>, } | { "action": "other", description: string, };

export type AnsweredQuestion = { question: string, answer: Array<string>, };

export type AskUserQuestionItem = { question: string, header: string, options: Array<AskUserQuestionOption>, multiSelect: boolean, };

export type AskUserQuestionOption = { label: string, description: string, };

export type TodoItem = { content: string, status: string, priority: string | null, };

export type NormalizedEntryError = { "type": "setup_required" } | { "type": "other" };

export type ToolResult = { type: ToolResultValueType, 
/**
 * For Markdown, this will be a JSON string; for JSON, a structured value
 */
value: JsonValue, };

export type ToolResultValueType = { "type": "markdown" } | { "type": "json" };

export type ToolStatus = { "status": "created" } | { "status": "success" } | { "status": "failed" } | { "status": "denied", reason: string | null, } | { "status": "pending_approval", approval_id: string, } | { "status": "timed_out" };

export type PatchType = { "type": "NORMALIZED_ENTRY", "content": NormalizedEntry } | { "type": "STDOUT", "content": string } | { "type": "STDERR", "content": string } | { "type": "DIFF", "content": Diff };

export type ModelInfo = { 
/**
 * Model identifier
 */
id: string, 
/**
 * Display name
 */
name: string, 
/**
 * Provider this model belongs to
 */
provider_id?: string | null, 
/**
 * Configurable reasoning options if supported
 */
reasoning_options: Array<ReasoningOption>, };

export type ReasoningOption = { id: string, label: string, is_default: boolean, };

export type ModelProvider = { 
/**
 * Provider identifier
 */
id: string, 
/**
 * Display name
 */
name: string, };

export type AgentInfo = { id: string, label: string, description?: string | null, is_default: boolean, };

export enum PermissionPolicy { AUTO = "AUTO", SUPERVISED = "SUPERVISED", PLAN = "PLAN" }

export type ModelSelectorConfig = { 
/**
 * Available providers
 */
providers: Array<ModelProvider>, 
/**
 * Available models
 */
models: Array<ModelInfo>, 
/**
 * Global default model (format: provider_id/model_id)
 */
default_model?: string | null, 
/**
 * Available agents
 */
agents: Array<AgentInfo>, 
/**
 * Supported permission policies
 */
permissions: Array<PermissionPolicy>, };

export type ExecutorDiscoveredOptions = { model_selector: ModelSelectorConfig, slash_commands: Array<SlashCommandDescription>, loading_models: boolean, loading_agents: boolean, loading_slash_commands: boolean, error: string | null, };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;

export type RelayWsMessageType = "text" | "binary" | "ping" | "pong" | "close";

export type DataChannelMessage = { "type": "http_request" } & DataChannelRequest | { "type": "http_response" } & DataChannelResponse | { "type": "ws_open" } & WsOpen | { "type": "ws_opened" } & WsOpened | { "type": "ws_frame" } & WsFrame | { "type": "ws_close" } & WsClose | { "type": "ws_error" } & WsError;

export type DataChannelRequest = { id: string, method: string, path: string, headers: { [key in string]?: Array<string> }, 
/**
 * Base64-encoded request body, if any.
 */
body_b64?: string | null, };

export type DataChannelResponse = { id: string, status: number, headers: { [key in string]?: Array<string> }, 
/**
 * Base64-encoded response body, if any.
 */
body_b64?: string | null, };

export type WsOpen = { 
/**
 * Unique connection ID for multiplexing.
 */
conn_id: string, 
/**
 * Target path, e.g. `/api/sessions/abc/queue`.
 */
path: string, 
/**
 * Optional sub-protocol(s) to negotiate.
 */
protocols?: string | null, };

export type WsOpened = { conn_id: string, 
/**
 * The sub-protocol selected by the server, if any.
 */
selected_protocol?: string | null, };

export type WsFrame = { conn_id: string, msg_type: RelayWsMessageType, 
/**
 * Base64-encoded payload.
 */
payload_b64?: string | null, };

export type WsClose = { conn_id: string, 
/**
 * Close code (RFC 6455 §7.4).
 */
code?: number | null, 
/**
 * Close reason.
 */
reason?: string | null, };

export type WsError = { conn_id: string, error: string, };

export type SdpOffer = { 
/**
 * The SDP string from the peer's `RTCPeerConnection.createOffer()`.
 */
sdp: string, 
/**
 * Caller-provided session identifier to correlate offer/answer/candidates.
 */
session_id: string, };

export type SdpAnswer = { 
/**
 * The SDP string from `Rtc::direct_api().create_answer()`.
 */
sdp: string, 
/**
 * Echoed session identifier from the offer.
 */
session_id: string, };

export const DEFAULT_PR_DESCRIPTION_PROMPT = "Update the PR that was just created with a better title and description.\nThe PR number is #{pr_number} and the URL is {pr_url}.\n\nAnalyze the changes in this branch and write:\n1. A concise, descriptive title that summarizes the changes, postfixed with \"(Vibe Kanban)\"\n2. A detailed description that explains:\n   - What changes were made\n   - Why they were made (based on the task context)\n   - Any important implementation details\n   - At the end, include a note: \"This PR was written using [Vibe Kanban](https://vibekanban.com)\"\n\nUse the appropriate CLI tool to update the PR (gh pr edit for GitHub, az repos pr update for Azure DevOps).";

export const DEFAULT_COMMIT_REMINDER_PROMPT = "There are uncommitted changes. Please stage and commit them now with a descriptive commit message.";