#!/bin/sh
# Vibe Kanban GitHub owner router. Generated by Vibe Kanban; edits are
# overwritten. Chooses GH_TOKEN for the GitHub owner a `gh` command targets,
# from the per-owner tokens configured in Settings -> Repositories, then runs
# the next `gh` on PATH. Never prints a token.
set -u
set -f

VK_SHIM_DIR=__VK_SHIM_DIR__
vk_ifs=$IFS

# Print the owner of a GitHub.com repository target, or nothing.
vk_owner_of() {
  vk_t=$1
  vk_p=""
  case "$vk_t" in
    https://github.com/*) vk_p=${vk_t#https://github.com/} ;;
    https://*@github.com/*) vk_p=${vk_t#https://*@github.com/} ;;
    ssh://git@github.com/*) vk_p=${vk_t#ssh://git@github.com/} ;;
    git@github.com:*) vk_p=${vk_t#git@github.com:} ;;
    github.com/*) vk_p=${vk_t#github.com/} ;;
    *://* | *@*:*) return 0 ;;
    */*)
      # A bare OWNER/REPO is on GH_HOST, or on `gh api --hostname` for an API path.
      case "${vk_target_host:-${GH_HOST:-}}" in
        "" | github.com) vk_p=$vk_t ;;
        *) return 0 ;;
      esac
      ;;
    *) return 0 ;;
  esac
  vk_o=${vk_p%%/*}
  vk_rest=${vk_p#*/}
  [ "$vk_rest" != "$vk_p" ] || return 0
  vk_r=${vk_rest%%/*}
  vk_r=${vk_r%.git}
  [ -n "$vk_o" ] && [ -n "$vk_r" ] || return 0
  case "$vk_o" in
    *[!A-Za-z0-9-]*) return 0 ;;
  esac
  printf '%s' "$vk_o"
}

# Flags whose separate value can look like a repository or URL (PR bodies,
# titles, templates, JSON fields, ...). An argument right after one of these is
# that flag's value, never a target. Boolean flags are not listed, so
# `gh repo create --private OWNER/REPO` still selects OWNER.
#
# Long flag names mean the same thing everywhere. Short letters do not: gh
# reuses them (`pr review -a` approves, `pr merge -d` deletes the branch), so
# short flags are looked up per command and subcommand.
vk_takes_value() {
  case "$1" in
    --body | --title | --notes | --description | --template | --json | --jq | \
      --field | --raw-field | --head | --header | --base | --search | --label | \
      --assignee | --reviewer | --milestone | --source | --remote | --limit | \
      --homepage | --method | --input | --subject | --body-file | --hostname | \
      --branch | --remote-name | --fork-name | --org | --visibility | --team | \
      --gitignore | --license | --add-topic | --remove-topic | --default-branch | \
      --upstream-remote-name | --author | --state | --project | --comment | \
      --reason | --notes-file | --author-email)
      return 0
      ;;
    -?) vk_short_takes_value "$1" ;;
    *) return 1 ;;
  esac
}

vk_short_takes_value() {
  case "$vk_cmd" in
    repo)
      case "$1" in -b | -d | -u | -l | -t | -p) return 0 ;; esac
      ;;
    api | workflow)
      case "$1" in -t | -p | -f | -F | -H | -X | -q) return 0 ;; esac
      ;;
    release)
      case "$1" in -n | -F | -t) return 0 ;; esac
      ;;
    pr | issue)
      case "$1" in
        -b | -F | -t | -T | -l | -L | -S | -A | -B | -H | -p | -q) return 0 ;;
        # Booleans in some subcommands: `pr review -a` (approve), `pr merge
        # -m/-s` (merge/squash), `pr view -c` (comments), `pr review -r`.
        -a)
          [ "$vk_sub" != review ]
          return
          ;;
        -m | -s)
          [ "$vk_sub" != merge ]
          return
          ;;
        -c)
          [ "$vk_sub" = close ]
          return
          ;;
        -r)
          [ "$vk_cmd $vk_sub" = "pr create" ] || [ "$vk_cmd $vk_sub" = "issue close" ]
          return
          ;;
      esac
      ;;
  esac
  return 1
}

vk_flag_repo=""
vk_api_host=""
vk_target_host=""
vk_api=""
vk_url=""
vk_repo_pos=""
vk_cmd=""
vk_sub=""
vk_state=cmd
vk_expect=""
vk_prev=""
# After `--` nothing is an option, but positionals still name targets
# (`gh repo view -- OWNER/REPO`).
vk_dashdash=""
for vk_arg do
  if [ -n "$vk_expect" ]; then
    vk_flag_repo=$vk_arg
    vk_expect=""
    vk_prev=""
    continue
  fi
  vk_positional=1
  if [ -z "$vk_dashdash" ]; then
    # The value of a value-taking flag is consumed first, even if it looks
    # like an option (`--body '--repo=OWNER/REPO'`).
    if vk_takes_value "$vk_prev"; then
      [ "$vk_prev" = --hostname ] && vk_api_host=$vk_arg
      vk_prev=""
      continue
    fi
    case "$vk_arg" in
      --)
        vk_dashdash=1
        vk_prev=""
        continue
        ;;
      -R | --repo)
        vk_expect=1
        continue
        ;;
      --repo=*)
        vk_flag_repo=${vk_arg#--repo=}
        vk_prev=""
        continue
        ;;
      -R?*)
        vk_flag_repo=${vk_arg#-R}
        vk_prev=""
        continue
        ;;
      --hostname=*)
        vk_api_host=${vk_arg#--hostname=}
        vk_prev=""
        continue
        ;;
      -*) vk_positional="" ;;
    esac
  fi
  vk_prev=$vk_arg
  case "$vk_state" in
    cmd)
      if [ -n "$vk_positional" ]; then
        vk_cmd=$vk_arg
        vk_state=sub
      fi
      ;;
    sub)
      # The subcommand selects the short-flag table (`vk_short_takes_value`).
      if [ -n "$vk_positional" ]; then
        vk_sub=$vk_arg
        vk_state=rest
        # Only these `gh repo` subcommands take a repository as their first
        # positional; others (`rename NEW-NAME`) keep GH_REPO / cwd routing.
        if [ "$vk_cmd" = repo ]; then
          case "$vk_sub" in
            view | clone | fork | delete | archive | unarchive | edit | sync | create | set-default)
              vk_state=target
              ;;
          esac
        fi
      fi
      ;;
    target)
      # The first positional that parses as a GitHub repository, so a value of
      # an unlisted flag (`--branch main`) cannot stand in for it.
      if [ -n "$vk_positional" ] && [ -n "$(vk_owner_of "$vk_arg")" ]; then
        vk_repo_pos=$vk_arg
        vk_state=rest
      fi
      ;;
  esac
  [ -n "$vk_positional" ] || continue
  if [ "$vk_cmd" = api ] && [ -z "$vk_api" ]; then
    case "$vk_arg" in
      repos/*/*) vk_api=${vk_arg#repos/} ;;
      /repos/*/*) vk_api=${vk_arg#/repos/} ;;
      https://api.github.com/repos/*/*) vk_api=github.com/${vk_arg#https://api.github.com/repos/} ;;
    esac
  fi
  if [ -z "$vk_url" ]; then
    case "$vk_arg" in
      https://github.com/*/*) vk_url=$vk_arg ;;
    esac
  fi
done

vk_api_owner=""
if [ -n "$vk_api" ]; then
  vk_target_host=$vk_api_host
  vk_api_owner="$(vk_owner_of "$vk_api")"
  vk_target_host=""
fi

vk_target=""
if [ -n "$vk_flag_repo" ]; then
  vk_target=$vk_flag_repo
elif [ -n "$vk_api_owner" ]; then
  # `repos/{owner}/{repo}` placeholders are filled by gh from the current
  # repository, so an API path without a literal owner falls through to it.
  vk_target=$vk_api
  vk_target_host=$vk_api_host
elif [ -n "$vk_url" ]; then
  vk_target=$vk_url
elif [ -n "$vk_repo_pos" ]; then
  vk_target=$vk_repo_pos
elif [ -n "${GH_REPO:-}" ]; then
  # gh itself uses GH_REPO instead of the current repository.
  vk_target=$GH_REPO
elif command -v git >/dev/null 2>&1; then
  # `gh repo set-default` records its choice as remote.<name>.gh-resolved:
  # "base" selects that remote, anything else is an explicit OWNER/REPO. gh
  # prefers it over push configuration, so it is checked first.
  vk_remote=""
  vk_resolved="$(git config --get-regexp '^remote\..*\.gh-resolved$' 2>/dev/null | head -n 1 || true)"
  if [ -n "$vk_resolved" ]; then
    vk_resolved_name=${vk_resolved%% *}
    vk_resolved_name=${vk_resolved_name#remote.}
    vk_resolved_name=${vk_resolved_name%.gh-resolved}
    vk_resolved_value=${vk_resolved#* }
    if [ "$vk_resolved_value" = base ]; then
      vk_remote=$vk_resolved_name
    else
      vk_target=$vk_resolved_value
    fi
  fi
  if [ -z "$vk_remote" ] && [ -z "$vk_target" ]; then
    vk_remote="$(git config --get remote.pushDefault 2>/dev/null || true)"
  fi
  vk_branch="$(git symbolic-ref --quiet --short HEAD 2>/dev/null || true)"
  if [ -z "$vk_remote" ] && [ -z "$vk_target" ] && [ -n "$vk_branch" ]; then
    vk_remote="$(git config --get "branch.$vk_branch.pushRemote" 2>/dev/null || true)"
  fi
  if [ -z "$vk_remote" ] && [ -z "$vk_target" ] && [ -n "$vk_branch" ]; then
    vk_remote="$(git config --get "branch.$vk_branch.remote" 2>/dev/null || true)"
  fi
  if [ -z "$vk_remote" ] && [ -z "$vk_target" ] && git remote get-url origin >/dev/null 2>&1; then
    vk_remote=origin
  fi
  if [ -z "$vk_remote" ] && [ -z "$vk_target" ]; then
    vk_remotes="$(git remote 2>/dev/null || true)"
    if [ -n "$vk_remotes" ] && [ "$(printf '%s\n' "$vk_remotes" | wc -l | tr -d ' ')" = 1 ]; then
      vk_remote=$vk_remotes
    fi
  fi
  if [ -n "$vk_remote" ] && [ "$vk_remote" != "." ]; then
    vk_target="$(git remote get-url "$vk_remote" 2>/dev/null || true)"
  fi
fi

vk_owner=""
if [ -n "$vk_target" ]; then
  vk_owner="$(vk_owner_of "$vk_target")"
fi

if [ -n "$vk_owner" ]; then
  vk_lower="$(printf '%s' "$vk_owner" | tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' 'abcdefghijklmnopqrstuvwxyz')"
  vk_configured=""
  IFS=,
  for vk_o in ${VK_GITHUB_ROUTED_OWNERS:-}; do
    if [ "$(printf '%s' "$vk_o" | tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' 'abcdefghijklmnopqrstuvwxyz')" = "$vk_lower" ]; then
      vk_configured=1
    fi
  done
  IFS=$vk_ifs
  if [ -n "$vk_configured" ]; then
    # Upper-case hex of the lower-cased owner, matching `token_env_name`: only
    # 0-9A-F, so the name is a safe variable name and cannot spell KEY, TOKEN
    # or SECRET (which some agent CLIs filter out).
    vk_key="$(printf '%s' "$vk_lower" | od -An -v -tx1 | tr -d ' \n' | tr 'abcdef' 'ABCDEF')"
    eval "vk_token=\${VK_GITHUB_PAT_$vk_key:-}"
    if [ -z "$vk_token" ]; then
      echo "gh: configured GitHub token for $vk_lower is unavailable; re-save it in Settings -> Repositories" >&2
      exit 78
    fi
    GH_TOKEN=$vk_token
    export GH_TOKEN
  fi
fi

vk_real=""
IFS=:
for vk_dir in $PATH; do
  [ -n "$vk_dir" ] || continue
  [ "$vk_dir" = "$VK_SHIM_DIR" ] && continue
  vk_candidate="$vk_dir/gh"
  if [ -f "$vk_candidate" ] && [ -x "$vk_candidate" ]; then
    if [ "$vk_candidate" -ef "$VK_SHIM_DIR/gh" ]; then
      continue
    fi
    vk_real=$vk_candidate
    break
  fi
done
IFS=$vk_ifs

if [ -z "$vk_real" ]; then
  echo "gh: GitHub CLI not found on PATH (after the Vibe Kanban shim)" >&2
  exit 127
fi
exec "$vk_real" "$@"
