#!/bin/sh
# Vibe Kanban GitHub owner router. Generated by Vibe Kanban; edits are
# overwritten. Chooses GH_TOKEN for the GitHub owner a `gh` command targets,
# from the per-owner tokens configured in Settings -> Repositories, then runs
# the next `gh` on PATH. Never prints a token.
set -u
set -f

VK_SHIM_DIR=__VK_SHIM_DIR__
vk_ifs=$IFS

# Print the owner of a GitHub.com repository target, or nothing.
vk_owner_of() {
  vk_t=$1
  vk_p=""
  case "$vk_t" in
    https://github.com/*) vk_p=${vk_t#https://github.com/} ;;
    https://*@github.com/*) vk_p=${vk_t#https://*@github.com/} ;;
    ssh://git@github.com/*) vk_p=${vk_t#ssh://git@github.com/} ;;
    git@github.com:*) vk_p=${vk_t#git@github.com:} ;;
    github.com/*) vk_p=${vk_t#github.com/} ;;
    *://* | *@*:*) return 0 ;;
    */*)
      case "${GH_HOST:-}" in
        "" | github.com) vk_p=$vk_t ;;
        *) return 0 ;;
      esac
      ;;
    *) return 0 ;;
  esac
  vk_o=${vk_p%%/*}
  vk_rest=${vk_p#*/}
  [ "$vk_rest" != "$vk_p" ] || return 0
  vk_r=${vk_rest%%/*}
  vk_r=${vk_r%.git}
  [ -n "$vk_o" ] && [ -n "$vk_r" ] || return 0
  case "$vk_o" in
    *[!A-Za-z0-9-]*) return 0 ;;
  esac
  printf '%s' "$vk_o"
}

vk_flag_repo=""
vk_api=""
vk_url=""
vk_repo_pos=""
vk_cmd=""
vk_state=cmd
vk_expect=""
for vk_arg do
  if [ -n "$vk_expect" ]; then
    vk_flag_repo=$vk_arg
    vk_expect=""
    continue
  fi
  case "$vk_arg" in
    --) break ;;
    -R | --repo)
      vk_expect=1
      continue
      ;;
    --repo=*)
      vk_flag_repo=${vk_arg#--repo=}
      continue
      ;;
  esac
  case "$vk_state" in
    cmd)
      case "$vk_arg" in
        -*) ;;
        *)
          vk_cmd=$vk_arg
          if [ "$vk_cmd" = repo ]; then vk_state=sub; else vk_state=rest; fi
          ;;
      esac
      ;;
    sub) vk_state=target ;;
    target)
      case "$vk_arg" in
        -*) ;;
        *) vk_repo_pos=$vk_arg ;;
      esac
      vk_state=rest
      ;;
  esac
  if [ "$vk_cmd" = api ] && [ -z "$vk_api" ]; then
    case "$vk_arg" in
      repos/*/*) vk_api=${vk_arg#repos/} ;;
      /repos/*/*) vk_api=${vk_arg#/repos/} ;;
    esac
  fi
  if [ -z "$vk_url" ]; then
    case "$vk_arg" in
      https://github.com/*/*) vk_url=$vk_arg ;;
    esac
  fi
done

vk_target=""
if [ -n "$vk_flag_repo" ]; then
  vk_target=$vk_flag_repo
elif [ -n "$vk_api" ]; then
  vk_target=$vk_api
elif [ -n "$vk_url" ]; then
  vk_target=$vk_url
elif [ -n "$vk_repo_pos" ]; then
  vk_target=$vk_repo_pos
elif command -v git >/dev/null 2>&1; then
  vk_remote="$(git config --get remote.pushDefault 2>/dev/null || true)"
  vk_branch="$(git symbolic-ref --quiet --short HEAD 2>/dev/null || true)"
  if [ -z "$vk_remote" ] && [ -n "$vk_branch" ]; then
    vk_remote="$(git config --get "branch.$vk_branch.pushRemote" 2>/dev/null || true)"
  fi
  if [ -z "$vk_remote" ] && [ -n "$vk_branch" ]; then
    vk_remote="$(git config --get "branch.$vk_branch.remote" 2>/dev/null || true)"
  fi
  if [ -z "$vk_remote" ] && git remote get-url origin >/dev/null 2>&1; then
    vk_remote=origin
  fi
  if [ -z "$vk_remote" ]; then
    vk_remotes="$(git remote 2>/dev/null || true)"
    if [ -n "$vk_remotes" ] && [ "$(printf '%s\n' "$vk_remotes" | wc -l | tr -d ' ')" = 1 ]; then
      vk_remote=$vk_remotes
    fi
  fi
  if [ -n "$vk_remote" ] && [ "$vk_remote" != "." ]; then
    vk_target="$(git remote get-url "$vk_remote" 2>/dev/null || true)"
  fi
fi

vk_owner=""
if [ -n "$vk_target" ]; then
  vk_owner="$(vk_owner_of "$vk_target")"
fi

if [ -n "$vk_owner" ]; then
  vk_lower="$(printf '%s' "$vk_owner" | tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' 'abcdefghijklmnopqrstuvwxyz')"
  vk_configured=""
  IFS=,
  for vk_o in ${VK_GITHUB_PAT_OWNERS:-}; do
    if [ "$(printf '%s' "$vk_o" | tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' 'abcdefghijklmnopqrstuvwxyz')" = "$vk_lower" ]; then
      vk_configured=1
    fi
  done
  IFS=$vk_ifs
  if [ -n "$vk_configured" ]; then
    # The owner is validated as [A-Za-z0-9-], so the variable name is safe.
    vk_key="$(printf '%s' "$vk_owner" | tr 'abcdefghijklmnopqrstuvwxyz-' 'ABCDEFGHIJKLMNOPQRSTUVWXYZ_')"
    eval "vk_token=\${VK_GITHUB_PAT_$vk_key:-}"
    if [ -z "$vk_token" ]; then
      echo "gh: configured GitHub token for $vk_lower is unavailable; re-save it in Settings -> Repositories" >&2
      exit 78
    fi
    GH_TOKEN=$vk_token
    export GH_TOKEN
  fi
fi

vk_real=""
IFS=:
for vk_dir in $PATH; do
  [ -n "$vk_dir" ] || continue
  [ "$vk_dir" = "$VK_SHIM_DIR" ] && continue
  vk_candidate="$vk_dir/gh"
  if [ -f "$vk_candidate" ] && [ -x "$vk_candidate" ]; then
    if [ "$vk_candidate" -ef "$VK_SHIM_DIR/gh" ]; then
      continue
    fi
    vk_real=$vk_candidate
    break
  fi
done
IFS=$vk_ifs

if [ -z "$vk_real" ]; then
  echo "gh: GitHub CLI not found on PATH (after the Vibe Kanban shim)" >&2
  exit 127
fi
exec "$vk_real" "$@"
